/**
 * 国际竞赛数据 - 模拟数据
 * v22.5.0 Phase 1
 * 数据来源：各竞赛官网公开信息，手动整理
 */

const COMPETITIONS = [
    // ========== 数理科学类 ==========
    {
        id: 'amc',
        name: 'AMC',
        fullName: 'American Mathematics Competitions',
        cnName: '美国数学竞赛',
        category: 'math',
        difficulty: 4,
        prestige: 5,
        grades: ['8', '9', '10', '11', '12'],
        organizer: 'MAA (Mathematical Association of America)',
        website: 'https://www.maa.org/math-competitions',
        region: 'global',
        type: 'individual',
        format: '笔试 · 25 道选择题 · 75 分钟',
        date: 'AMC 8: 每年 1 月 / AMC 10/12: 每年 11 月',
        fee: '约 ¥100-200',
        intro: '美国数学协会主办的全美最重要数学竞赛，分 AMC 8/10/12 三个级别。成绩优异者可晋级 AIME 和 USAMO，是理工科申请者最核心的竞赛之一。',
        eligibility: 'AMC 8: 8 年级及以下 / AMC 10: 10 年级及以下 / AMC 12: 12 年级及以下',
        prepTime: '建议 3-6 个月系统备考',
        awards: '全球前 1% Distinguished Honor Roll / 前 5% Honor Roll',
        acceptanceRate: 'AMC 10 晋级 AIME 约 2.5%，AMC 12 约 5%',
        relatedMajors: ['cs', 'math', 'physics', 'engineering'],
        relatedComps: ['aime', 'usamo'],
        tags: ['数学', '顶级', '理工科必选'],
        featured: true
    },
    {
        id: 'aime',
        name: 'AIME',
        fullName: 'American Invitational Mathematics Examination',
        cnName: '美国数学邀请赛',
        category: 'math',
        difficulty: 5,
        prestige: 5,
        grades: ['10', '11', '12'],
        organizer: 'MAA',
        website: 'https://www.maa.org/math-competitions',
        region: 'global',
        type: 'individual',
        format: '笔试 · 15 道填空题 · 3 小时',
        date: '每年 2-3 月',
        fee: '通过学校报名，费用包含在 AMC 中',
        intro: 'AMC 10/12 成绩优异者受邀参加的进阶数学竞赛，15 道填空题难度显著提升，是晋级 USAMO 的必经之路。',
        eligibility: 'AMC 10/12 成绩达标者（约前 2.5%-5%）',
        prepTime: '需在 AMC 基础上再加强训练 2-3 个月',
        awards: 'AIME 成绩用于 USAMO 选拔，无单独奖项',
        acceptanceRate: '晋级 USAMO 约 500 人',
        relatedMajors: ['cs', 'math', 'physics'],
        relatedComps: ['amc', 'usamo'],
        tags: ['数学', '顶级', '邀请赛'],
        featured: true
    },
    {
        id: 'usamo',
        name: 'USA(J)MO',
        fullName: 'USA Mathematical Olympiad',
        cnName: '美国数学奥林匹克',
        category: 'math',
        difficulty: 5,
        prestige: 5,
        grades: ['10', '11', '12'],
        organizer: 'MAA',
        website: 'https://www.maa.org/math-competitions',
        region: 'us',
        type: 'individual',
        format: '笔试 · 6 道证明题 · 2 天每天 4.5 小时',
        date: '每年 3-4 月',
        fee: '免费（受邀参加）',
        intro: '美国最高级别数学竞赛，AMC+AIME 综合排名前约 500 人受邀参加。USAMO 成绩是藤校理工科申请的顶级加分项。',
        eligibility: 'AMC 10/12 + AIME 综合成绩达标者',
        prepTime: '需要数年数学竞赛训练积累',
        awards: 'Winner / Gold / Silver / Bronze / Honorable Mention',
        acceptanceRate: '约 500 人参赛，获奖约 100 人',
        relatedMajors: ['cs', 'math', 'physics'],
        relatedComps: ['amc', 'aime'],
        tags: ['数学', '顶级', '奥赛'],
        featured: false
    },
    {
        id: 'physics-bowl',
        name: 'Physics Bowl',
        fullName: 'Physics Bowl',
        cnName: '物理碗',
        category: 'math',
        difficulty: 3,
        prestige: 4,
        grades: ['9', '10', '11', '12'],
        organizer: 'AAPT (American Association of Physics Teachers)',
        website: 'https://www.aapt.org/programs/physicsbowl/',
        region: 'global',
        type: 'individual',
        format: '笔试 · 40 道选择题 · 45 分钟',
        date: '每年 3-4 月',
        fee: '约 ¥200-300',
        intro: '美国物理教师协会主办的物理竞赛，分 Division 1 和 Division 2 两个难度。考察范围广，适合有一定物理基础的学生。',
        eligibility: '高中生均可参加，Division 1 适合未学 AP Physics C 的学生',
        prepTime: '建议 2-3 个月',
        awards: '全球前 10 / 各赛区前 10',
        acceptanceRate: '全球约 10000 人参赛',
        relatedMajors: ['physics', 'engineering', 'cs'],
        relatedComps: ['ukcho', 'usnco'],
        tags: ['物理', '高频'],
        featured: true
    },
    {
        id: 'ukcho',
        name: 'UKChO',
       fullName: 'UK Chemistry Olympiad',
        cnName: '英国化学奥赛',
        category: 'math',
        difficulty: 4,
        prestige: 4,
        grades: ['11', '12'],
        organizer: 'Royal Society of Chemistry',
        website: 'https://edu.rsc.org/enrichment/uk-chemistry-olympiad',
        region: 'global',
        type: 'individual',
        format: '笔试 · 2 小时',
        date: '每年 1-2 月',
        fee: '约 ¥300',
        intro: '英国皇家化学学会主办的化学竞赛，难度较高，涉及大量超出高中课纲的化学知识。金奖成绩对申请化学、生物相关专业有较高含金量。',
        eligibility: '11-12 年级学生',
        prepTime: '建议 3-4 个月，需补充大学化学知识',
        awards: 'Gold / Silver / Bronze（Gold 约 8%）',
        acceptanceRate: 'Gold 约 8%，Silver 约 25%',
        relatedMajors: ['chemistry', 'biology', 'biochem'],
        relatedComps: ['usnco', 'bbo'],
        tags: ['化学', '高难度'],
        featured: false
    },
    {
        id: 'usnco',
        name: 'USNCO',
        fullName: 'US National Chemistry Olympiad',
        cnName: '美国化学奥赛',
        category: 'math',
        difficulty: 4,
        prestige: 4,
        grades: ['10', '11', '12'],
        organizer: 'American Chemical Society',
        website: 'https://www.acs.org/content/acs/en/education/students/highschool/olympiad.html',
        region: 'us',
        type: 'individual',
        format: '笔试（Local + National）· 多轮选拔',
        date: 'Local: 每年 3 月 / National: 每年 4 月',
        fee: '约 ¥200',
        intro: '美国化学会主办的全国化学竞赛，通过 Local Exam 和 National Exam 两轮选拔，最终 20 人进入集训营，4 人代表美国参加 IChO 国际化学奥赛。',
        eligibility: '美国公民或永久居民，高中生',
        prepTime: '建议 4-6 个月',
        awards: 'National Finalist（20 人）/ Honors',
        acceptanceRate: '约 1000 人参加 National Exam，20 人入选集训',
        relatedMajors: ['chemistry', 'biology', 'biochem'],
        relatedComps: ['ukcho', 'bbo'],
        tags: ['化学', '美国', '选拔赛'],
        featured: false
    },
    {
        id: 'bbo',
        name: 'BBO',
        fullName: 'British Biology Olympiad',
        cnName: '英国生物奥赛',
        category: 'math',
        difficulty: 3,
        prestige: 3,
        grades: ['9', '10', '11', '12'],
        organizer: 'Royal Society of Biology',
        website: 'https://www.rsb.org.uk/get-involved/british-biology-olympiad',
        region: 'global',
        type: 'individual',
        format: '笔试 · 选择题 · 90 分钟',
        date: '每年 2-3 月',
        fee: '约 ¥300',
        intro: '英国皇家生物学会主办的生物竞赛，难度适中，适合作为生物方向的入门竞赛。优秀者可受邀参加英国生物奥赛集训。',
        eligibility: '高中生均可参加',
        prepTime: '建议 2-3 个月',
        awards: 'Gold / Silver / Bronze / Highly Commended / Commended',
        acceptanceRate: 'Gold 约 5%，Silver 约 10%',
        relatedMajors: ['biology', 'biochem', 'neuroscience'],
        relatedComps: ['usabo', 'ukcho'],
        tags: ['生物', '入门友好'],
        featured: false
    },
    {
        id: 'usabo',
        name: 'USABO',
        fullName: 'USA Biology Olympiad',
        cnName: '美国生物奥赛',
        category: 'math',
        difficulty: 4,
        prestige: 4,
        grades: ['10', '11', '12'],
        organizer: 'Center for Excellence in Education',
        website: 'https://www.usabo-trc.org/',
        region: 'us',
        type: 'individual',
        format: '笔试 · Open Exam (50 选择题) + Semifinal (短答题)',
        date: 'Open: 每年 2 月 / Semifinal: 每年 3 月',
        fee: '约 ¥200',
        intro: '美国生物奥赛，通过 Open Exam 和 Semifinal 两轮选拔，最终 20 人进入集训营，4 人代表美国参加 IBO 国际生物奥赛。',
        eligibility: '美国公民或永久居民，高中生',
        prepTime: '建议 4-6 个月，需掌握大学水平生物学',
        awards: 'Semifinalist（约 500-1000 人）/ National Finalist（20 人）',
        acceptanceRate: 'Open 约 10000 人，Semifinalist 约 500-1000 人',
        relatedMajors: ['biology', 'biochem', 'neuroscience'],
        relatedComps: ['bbo', 'ukcho'],
        tags: ['生物', '美国', '选拔赛'],
        featured: false
    },

    // ========== 计算机与工程类 ==========
    {
        id: 'usaco',
        name: 'USACO',
        fullName: 'USA Computing Olympiad',
        cnName: '美国信息学奥赛',
        category: 'cs',
        difficulty: 5,
        prestige: 5,
        grades: ['9', '10', '11', '12'],
        organizer: 'USACO',
        website: 'http://www.usaco.org/',
        region: 'global',
        type: 'individual',
        format: '线上 · 3-4 道编程题 · 3-4 小时',
        date: '每年 12 月、1 月、2 月共 3 场月赛 + 公开赛',
        fee: '免费',
        intro: '美国计算机奥赛，分 Bronze/Silver/Gold/Platinum 四个级别。中国学生可参加，Platinum 级别成绩对 CS 申请有极高含金量。',
        eligibility: '全球中学生均可参加，从 Bronze 开始逐级晋升',
        prepTime: 'Bronze 到 Silver 约 2-3 个月，到 Gold 约 6 个月，到 Platinum 需 1 年+',
        awards: 'Platinum / Gold / Silver / Bronze 级别认证',
        acceptanceRate: 'Platinum 级别约前 200-300 人',
        relatedMajors: ['cs', 'se', 'ai', 'ds'],
        relatedComps: ['ccc'],
        tags: ['计算机', '顶级', '免费', '全球可参加'],
        featured: true
    },
    {
        id: 'ccc',
        name: 'CCC',
        fullName: 'Canadian Computing Competition',
        cnName: '加拿大计算机竞赛',
        category: 'cs',
        difficulty: 3,
        prestige: 3,
        grades: ['9', '10', '11', '12'],
        organizer: 'University of Waterloo',
        website: 'https://cemc.uwaterloo.ca/contests/computing-competition',
        region: 'global',
        type: 'individual',
        format: '笔试 · 5 道编程题 · 3 小时',
        date: '每年 2 月',
        fee: '约 ¥200',
        intro: '滑铁卢大学主办的计算机竞赛，分 Junior 和 Senior 两个级别。难度低于 USACO，适合作为入门级编程竞赛。',
        eligibility: '高中生均可参加',
        prepTime: '建议 2-3 个月',
        awards: 'Certificate of Distinction（各赛区前 25%）',
        acceptanceRate: '约 25% 获得 Distinction',
        relatedMajors: ['cs', 'se', 'ds'],
        relatedComps: ['usaco'],
        tags: ['计算机', '入门友好'],
        featured: false
    },
    {
        id: 'vex',
        name: 'VEX Robotics',
        fullName: 'VEX Robotics Competition',
        cnName: 'VEX 机器人竞赛',
        category: 'cs',
        difficulty: 4,
        prestige: 4,
        grades: ['6', '7', '8', '9', '10', '11', '12'],
        organizer: 'REC Foundation',
        website: 'https://www.vexrobotics.com/competition',
        region: 'global',
        type: 'team',
        format: '团队赛 · 搭建 + 编程 + 对抗赛',
        date: '全年滚动，区域赛 / 州赛 / 全国赛 / 世锦赛',
        fee: '注册费 + 器材费，约 ¥2000-5000/年',
        intro: '全球最大的机器人竞赛之一，团队合作完成机器人搭建、编程和对抗赛。世锦赛规模大，获奖对工程类申请有较高含金量。',
        eligibility: '中学生均可参加，分 VEX IQ / VEX EDR / VEX U',
        prepTime: '全年备赛，赛季持续 6-8 个月',
        awards: 'World Championship / Excellence Award / Tournament Champion 等',
        acceptanceRate: '全球数万支队伍，世锦赛约 800 队',
        relatedMajors: ['engineering', 'cs', 'me'],
        relatedComps: ['frc'],
        tags: ['机器人', '团队赛', '工程'],
        featured: true
    },
    {
        id: 'frc',
        name: 'FRC',
        fullName: 'FIRST Robotics Competition',
        cnName: 'FRC 机器人竞赛',
        category: 'cs',
        difficulty: 4,
        prestige: 4,
        grades: ['9', '10', '11', '12'],
        organizer: 'FIRST',
        website: 'https://www.firstinspires.org/robotics/frc',
        region: 'global',
        type: 'team',
        format: '团队赛 · 6 周内搭建大型机器人 + 对抗赛',
        date: '每年 1 月发布题目，3-4 月区域赛，4 月世锦赛',
        fee: '注册费 + 器材费，约 ¥5000-20000/年',
        intro: 'FIRST 旗下最高级别机器人竞赛，团队需在 6 周内设计搭建一台大型机器人。竞赛强度大，工程含量高，对工程类申请极有帮助。',
        eligibility: '高中生，需组队（通常以学校为单位）',
        prepTime: '赛季集中备赛 6 周，全年技术储备',
        awards: 'Chairman\'s Award / Engineering Inspiration / Regional Winner 等',
        acceptanceRate: '全球约 4000 队，世锦赛约 400 队',
        relatedMajors: ['engineering', 'me', 'cs'],
        relatedComps: ['vex'],
        tags: ['机器人', '团队赛', '工程', '高强度'],
        featured: false
    },
    {
        id: 'isef',
        name: 'ISEF',
        fullName: 'Regeneron International Science & Engineering Fair',
        cnName: '国际科学与工程大奖赛',
        category: 'cs',
        difficulty: 5,
        prestige: 5,
        grades: ['9', '10', '11', '12'],
        organizer: 'Society for Science',
        website: 'https://www.societyforscience.org/isef/',
        region: 'global',
        type: 'individual',
        format: '科研项目展示 + 评委答辩',
        date: '每年 5 月（需通过区域附属赛选拔）',
        fee: '免费（附属赛可能有报名费）',
        intro: '全球最大规模的高中生科学竞赛，需通过区域附属赛选拔晋级。获奖者可获得数万美元奖金，是科研类竞赛的天花板。',
        eligibility: '9-12 年级，需通过附属赛选拔',
        prepTime: '科研项目通常持续 6-12 个月',
        awards: 'Grand Awards（$75,000 / $50,000 等）+ Special Awards',
        acceptanceRate: '全球约 1800 人入围决赛',
        relatedMajors: ['cs', 'biology', 'chemistry', 'physics', 'engineering'],
        relatedComps: ['gsf', 'sts'],
        tags: ['科研', '顶级', '奖金高'],
        featured: true
    },
    {
        id: 'gsf',
        name: 'Google Science Fair',
        fullName: 'Google Science Fair',
        cnName: '谷歌科学挑战赛',
        category: 'cs',
        difficulty: 5,
        prestige: 5,
        grades: ['9', '10', '11', '12'],
        organizer: 'Google',
        website: 'https://www.googlesciencefair.com/',
        region: 'global',
        type: 'individual',
        format: '线上提交科研项目',
        date: '不定期举办（已暂停，关注官网）',
        fee: '免费',
        intro: 'Google 主办的全球科学竞赛，鼓励学生用科学方法解决实际问题。获奖者可获得 Google 奖学金和参观 Google 总部机会。',
        eligibility: '13-18 岁全球学生',
        prepTime: '项目周期 3-6 个月',
        awards: 'Grand Prize $50,000 + 各类别奖项',
        acceptanceRate: '全球数万参赛者，决赛约 20 人',
        relatedMajors: ['cs', 'engineering', 'biology', 'physics'],
        relatedComps: ['isef', 'sts'],
        tags: ['科研', '顶级', 'Google'],
        featured: false
    },

    // ========== 商科与经济类 ==========
    {
        id: 'nec',
        name: 'NEC',
        fullName: 'National Economics Challenge',
        cnName: '全美经济学挑战赛',
        category: 'business',
        difficulty: 3,
        prestige: 4,
        grades: ['9', '10', '11', '12'],
        organizer: 'Council for Economic Education',
        website: 'https://www.councilforeconed.org/programs/programs-for-students/national-economics-challenge/',
        region: 'global',
        type: 'team',
        format: '团队赛 · 笔试 + 抢答 + 辩论',
        date: '中国赛区 12 月 / 美国赛区 3-5 月',
        fee: '约 ¥500-800',
        intro: '全美最具影响力的经济学竞赛之一，分 David Ricardo 和 Adam Smith 两个组别。考察微观经济学、宏观经济学、国际经济等内容。',
        eligibility: '高中生，2-4 人组队',
        prepTime: '建议 3-4 个月',
        awards: 'National Champion / Regional Champion / 个人奖项',
        acceptanceRate: '中国赛区约 3000 人参赛',
        relatedMajors: ['econ', 'finance', 'business'],
        relatedComps: ['ieo', 'fbla'],
        tags: ['经济', '团队赛', '高频'],
        featured: true
    },
    {
        id: 'ieo',
        name: 'IEO',
        fullName: 'International Economics Olympiad',
        cnName: '国际经济学奥赛',
        category: 'business',
        difficulty: 4,
        prestige: 4,
        grades: ['9', '10', '11', '12'],
        organizer: 'IEO Committee',
        website: 'https://ieo-org.org/',
        region: 'global',
        type: 'team',
        format: '团队赛 · 经济学笔试 + 财务素养 + 商业案例分析',
        date: '每年 7-8 月（需通过国家选拔）',
        fee: '通过国家代表队选拔',
        intro: '国际经济学奥赛，13 项国际科学奥赛之一。需通过国家选拔后代表参赛，含金量极高。',
        eligibility: '需通过国家代表队选拔',
        prepTime: '需 1 年以上经济学竞赛积累',
        awards: 'Gold / Silver / Bronze Medals',
        acceptanceRate: '全球约 30 个国家代表队',
        relatedMajors: ['econ', 'finance', 'business'],
        relatedComps: ['nec', 'fbla'],
        tags: ['经济', '顶级', '奥赛'],
        featured: false
    },
    {
        id: 'fbla',
        name: 'FBLA',
        fullName: 'Future Business Leaders of America',
        cnName: '未来商业领袖',
        category: 'business',
        difficulty: 3,
        prestige: 3,
        grades: ['9', '10', '11', '12'],
        organizer: 'FBLA',
        website: 'https://www.fbla-pbl.org/',
        region: 'global',
        type: 'individual',
        format: '个人或团队 · 多个商业科目竞赛',
        date: '区域赛 1-2 月 / 全国赛 6-7 月',
        fee: '约 ¥300-500',
        intro: '美国最大的商科学生组织，提供 70+ 个竞赛项目，涵盖市场营销、会计、管理、创业等。门槛较低，适合商科入门。',
        eligibility: '高中生均可参加',
        prepTime: '建议 2-3 个月',
        awards: 'National Finalist / 各项目 Top 10',
        acceptanceRate: '全国赛约 12000 人参加',
        relatedMajors: ['business', 'marketing', 'accounting', 'finance'],
        relatedComps: ['deca', 'nec'],
        tags: ['商科', '多项目', '入门友好'],
        featured: false
    },
    {
        id: 'deca',
        name: 'DECA',
        fullName: 'Distributive Education Clubs of America',
        cnName: 'DECA 商业挑战赛',
        category: 'business',
        difficulty: 3,
        prestige: 3,
        grades: ['9', '10', '11', '12'],
        organizer: 'DECA Inc.',
        website: 'https://www.deca.org/',
        region: 'global',
        type: 'individual',
        format: '个人或团队 · 案例分析 + 角色扮演 + 笔试',
        date: '区域赛 12-1 月 / 州赛 2-3 月 / 全国赛 4-5 月',
        fee: '约 ¥300-500',
        intro: '与 FBLA 齐名的商科竞赛，侧重营销、管理和创业。比赛形式以案例分析和角色扮演为主，注重实战能力。',
        eligibility: '高中生均可参加',
        prepTime: '建议 2-3 个月',
        awards: 'International Champion / Top 10 等',
        acceptanceRate: '全国赛约 20000 人',
        relatedMajors: ['marketing', 'business', 'management'],
        relatedComps: ['fbla', 'nec'],
        tags: ['商科', '营销', '实战'],
        featured: false
    },
    {
        id: 'kwhs',
        name: 'KWHS',
        fullName: 'Knowledge at Wharton High School',
        cnName: '沃顿商赛',
        category: 'business',
        difficulty: 4,
        prestige: 5,
        grades: ['9', '10', '11', '12'],
        organizer: 'Wharton School, UPenn',
        website: 'https://kwhs.wharton.upenn.edu/',
        region: 'global',
        type: 'team',
        format: '团队赛 · 投资策略报告 + 答辩',
        date: '每年 9 月开始，12 月提交报告',
        fee: '免费',
        intro: '沃顿商学院主办的高中生投资竞赛，全球最具含金量的商科竞赛之一。团队需制定投资策略并提交报告，获奖对商科申请极有帮助。',
        eligibility: '4-7 人组队，高中生',
        prepTime: '约 3 个月（9-12 月）',
        awards: 'Global Top 10 / Regional Finalist',
        acceptanceRate: '全球约 5000 队参赛',
        relatedMajors: ['finance', 'business', 'econ'],
        relatedComps: ['nec', 'fbla'],
        tags: ['商科', '顶级', '沃顿', '免费'],
        featured: true
    },

    // ========== 人文社科类 ==========
    {
        id: 'nshdlc',
        name: 'NHSDLC',
        fullName: 'National High School Debate League of China',
        cnName: '中国高中生美式辩论联赛',
        category: 'humanities',
        difficulty: 3,
        prestige: 3,
        grades: ['7', '8', '9', '10', '11', '12'],
        organizer: 'NHSDLC',
        website: 'https://www.nshdlc.com/',
        region: 'china',
        type: 'team',
        format: '团队赛（2 人）· 美式辩论',
        date: '全年滚动，区域赛 / 全国赛',
        fee: '约 ¥500-1000/场',
        intro: '中国最大的美式辩论联赛，全年多场区域赛。辩论话题涉及政治、经济、社会等，锻炼批判性思维和英语表达。',
        eligibility: '7-12 年级',
        prepTime: '每场备赛 2-4 周',
        awards: 'Champion / Finalist / Best Speaker 等',
        acceptanceRate: '每场约 100-200 队',
        relatedMajors: ['polisci', 'ir', 'sociology', 'comm'],
        relatedComps: ['nsda'],
        tags: ['辩论', '英语', '中国'],
        featured: false
    },
    {
        id: 'nsda',
        name: 'NSDA',
        fullName: 'National Speech & Debate Association',
        cnName: '美国演讲与辩论协会',
        category: 'humanities',
        difficulty: 4,
        prestige: 4,
        grades: ['6', '7', '8', '9', '10', '11', '12'],
        organizer: 'NSDA',
        website: 'https://www.speechanddebate.org/',
        region: 'global',
        type: 'individual',
        format: '个人或团队 · 多种辩论和演讲形式',
        date: '全年滚动，全国赛 6 月',
        fee: '约 ¥300/场',
        intro: '美国最大演讲辩论组织，提供 PF / LD / Policy / Congress 等多种辩论形式。全国赛获奖对人文社科申请有较高含金量。',
        eligibility: '6-12 年级',
        prepTime: '持续训练，每场备赛 2-4 周',
        awards: 'National Champion / 各赛事 Top 10',
        acceptanceRate: '全国赛约 6000 人参加',
        relatedMajors: ['polisci', 'ir', 'comm', 'sociology'],
        relatedComps: ['nshdlc'],
        tags: ['辩论', '演讲', '美国'],
        featured: true
    },
    {
        id: 'john-locke',
        name: 'John Locke',
        fullName: 'John Locke Institute Essay Competition',
        cnName: '约翰·洛克论文竞赛',
        category: 'humanities',
        difficulty: 5,
        prestige: 5,
        grades: ['10', '11', '12'],
        organizer: 'John Locke Institute',
        website: 'https://www.johnlockinstitute.com/essay-competition',
        region: 'global',
        type: 'individual',
        format: '个人 · 论文写作（2000-4000 词）',
        date: '每年 1-6 月提交，7 月公布结果',
        fee: '约 ¥500',
        intro: '牛津大学约翰·洛克研究所主办的论文竞赛，涵盖哲学、政治、经济、历史、法律、心理学、神学 7 个领域。获奖对人文社科申请有顶级含金量。',
        eligibility: '10-12 年级（18 岁以下）',
        prepTime: '建议 2-3 个月深入研究和写作',
        awards: '各学科 Best Essay / Overall Best Essay（$2000 奖学金）',
        acceptanceRate: '全球数千人参赛，获奖率约 1-2%',
        relatedMajors: ['philosophy', 'polisci', 'history', 'econ', 'psych'],
        relatedComps: ['marshall-essay', 'concord-review'],
        tags: ['写作', '顶级', '论文', '人文'],
        featured: true
    },
    {
        id: 'marshall-essay',
        name: 'Marshall Essay',
        fullName: 'Marshall Society Essay Competition',
        cnName: '马歇尔学会论文竞赛',
        category: 'humanities',
        difficulty: 5,
        prestige: 5,
        grades: ['11', '12'],
        organizer: 'Marshall Society, Cambridge',
        website: 'https://wwwmarshallsociety.com/essay-competition/',
        region: 'global',
        type: 'individual',
        format: '个人 · 经济学论文（1000-1500 词）',
        date: '每年 7-8 月提交，9 月公布',
        fee: '免费',
        intro: '剑桥大学马歇尔学会主办的经济学论文竞赛，与 John Locke 齐名。考察经济学分析能力和写作水平，对经济类申请有顶级含金量。',
        eligibility: '11-12 年级',
        prepTime: '建议 1-2 个月',
        awards: 'Winner / Runners-up / Shortlist',
        acceptanceRate: '全球数百人参赛，获奖率约 5%',
        relatedMajors: ['econ', 'finance'],
        relatedComps: ['john-locke', 'nec'],
        tags: ['写作', '顶级', '经济', '免费'],
        featured: false
    },
    {
        id: 'himcm',
        name: 'HiMCM',
        fullName: 'High School Mathematical Contest in Modeling',
        cnName: '美国高中生数学建模竞赛',
        category: 'humanities',
        difficulty: 4,
        prestige: 4,
        grades: ['9', '10', '11', '12'],
        organizer: 'COMAP',
        website: 'https://www.comap.com/highschool/contests/himcm/',
        region: 'global',
        type: 'team',
        format: '团队赛（3-4 人）· 36 小时内完成数学建模论文',
        date: '每年 11 月',
        fee: '约 ¥600/队',
        intro: '美国数学及其应用联合会主办的数学建模竞赛，团队需在 36 小时内完成开放性问题的数学建模和论文。考察数学应用、编程和团队协作。',
        eligibility: '9-12 年级，3-4 人组队',
        prepTime: '建议赛前 2-3 个月学习建模方法',
        awards: 'Outstanding / Finalist / Meritorious / Honorable Mention',
        acceptanceRate: 'Outstanding 约 1%，Finalist 约 7%',
        relatedMajors: ['math', 'cs', 'ds', 'engineering'],
        relatedComps: ['amc', 'mmm'],
        tags: ['数学建模', '团队赛', '论文'],
        featured: false
    },
    {
        id: 'ctb',
        name: 'CTB',
        fullName: 'China Thinks Big',
        cnName: '全球创新研究大挑战',
        category: 'humanities',
        difficulty: 3,
        prestige: 3,
        grades: ['9', '10', '11', '12'],
        organizer: 'Harvard Business School',
        website: 'https://www.chinathinksbig.org/',
        region: 'china',
        type: 'team',
        format: '团队赛 · 课题研究 + 项目实践 + 答辩',
        date: '每年 11 月启动，3-4 月全国赛',
        fee: '约 ¥1500-3000',
        intro: '由哈佛商学院发起的创新研究竞赛，团队选择社会问题进行研究并提出创新方案。考察研究能力、创新思维和团队协作。',
        eligibility: '9-12 年级，4-8 人组队',
        prepTime: '约 4 个月',
        awards: 'Global Finalist / National Gold/Silver/Bronze',
        acceptanceRate: '全国约 2000 队，Global Finalist 约 50 队',
        relatedMajors: ['sociology', 'comm', 'business', 'ir'],
        relatedComps: ['nshdlc', 'isef'],
        tags: ['创新', '研究', '团队赛', '中国'],
        featured: false
    },

    // ========== 艺术与写作类 ==========
    {
        id: 'scholastic',
        name: 'Scholastic',
        fullName: 'Scholastic Art & Writing Awards',
        cnName: '学术艺术与写作奖',
        category: 'arts',
        difficulty: 3,
        prestige: 4,
        grades: ['7', '8', '9', '10', '11', '12'],
        organizer: 'Alliance for Young Artists & Writers',
        website: 'https://www.artandwriting.org/',
        region: 'us',
        type: 'individual',
        format: '个人 · 提交艺术或写作作品',
        date: '每年 9-12 月提交，3 月公布',
        fee: '约 ¥50-100/件',
        intro: '美国最历史悠久的学生艺术写作竞赛，涵盖 28 个艺术类别和 11 个写作类别。Gold Key 获奖作品进入全国评选。',
        eligibility: '7-12 年级，美国/加拿大学生或在美就读国际生',
        prepTime: '取决于作品，通常 1-3 个月',
        awards: 'Gold Key / Silver Key / Honorable Mention / National Medal',
        acceptanceRate: 'Gold Key 约 7%，National Medal 约 0.5%',
        relatedMajors: ['arts', 'design', 'music', 'comm'],
        relatedComps: ['youngarts', 'concord-review'],
        tags: ['艺术', '写作', '多类别'],
        featured: false
    },
    {
        id: 'youngarts',
        name: 'YoungArts',
        fullName: 'National YoungArts Foundation',
        cnName: '国家青年艺术基金会',
        category: 'arts',
        difficulty: 4,
        prestige: 5,
        grades: ['10', '11', '12'],
        organizer: 'National YoungArts Foundation',
        website: 'https://youngarts.org/',
        region: 'us',
        type: 'individual',
        format: '个人 · 提交作品集 + 面试',
        date: '每年 10 月提交，1 月公布',
        fee: '约 ¥200',
        intro: '美国最高级别青年艺术竞赛，涵盖视觉艺术、表演艺术、文学等 10 个领域。获奖者可参加纽约艺术周并获总统学者提名。',
        eligibility: '15-18 岁，美国公民或永久居民',
        prepTime: '需长期艺术积累 + 作品集准备 3-6 个月',
        awards: 'Finalist / Honorable Mention / Merit',
        acceptanceRate: '约 7000 人申请，Finalist 约 150 人',
        relatedMajors: ['arts', 'music', 'design', 'comm'],
        relatedComps: ['scholastic'],
        tags: ['艺术', '顶级', '美国'],
        featured: false
    },
    {
        id: 'concord-review',
        name: 'Concord Review',
        fullName: 'The Concord Review',
        cnName: '历史评论季刊',
        category: 'writing',
        difficulty: 4,
        prestige: 5,
        grades: ['9', '10', '11', '12'],
        organizer: 'The Concord Review, Inc.',
        website: 'https://www.tcr.org/',
        region: 'global',
        type: 'individual',
        format: '个人 · 历史研究论文（4000-6000 词）',
        date: '滚动提交，每季度评选',
        fee: '约 ¥500',
        intro: '全球唯一刊登高中生历史论文的学术期刊，发表率极低。被哈佛招生官列为最看重的课外学术活动之一。',
        eligibility: '高中生均可投稿',
        prepTime: '论文写作约 3-6 个月',
        awards: '发表在 The Concord Review / Emerson Prize',
        acceptanceRate: '投稿发表率约 5%',
        relatedMajors: ['history', 'polisci', 'ir', 'anthropology'],
        relatedComps: ['john-locke', 'marshall-essay'],
        tags: ['历史', '写作', '顶级', '期刊'],
        featured: false
    },
    {
        id: 'nyt-contest',
        name: 'NYT Contest',
        fullName: 'New York Times Student Contests',
        cnName: '纽约时报学生竞赛',
        category: 'writing',
        difficulty: 3,
        prestige: 4,
        grades: ['9', '10', '11', '12'],
        organizer: 'The New York Times',
        website: 'https://www.nytimes.com/section/learning/contests',
        region: 'global',
        type: 'individual',
        format: '个人 · 多种写作形式（社论、评论、叙事等）',
        date: '全年多个竞赛，1-4 月最集中',
        fee: '免费',
        intro: '纽约时报主办的学生写作竞赛系列，包含社论写作、书评、叙事写作等多个类别。获奖作品可在纽约时报发表。',
        eligibility: '11-19 岁全球学生',
        prepTime: '每个竞赛 1-2 周',
        awards: 'Winner / Runners-up / Honorable Mention',
        acceptanceRate: '每个竞赛数千人参赛，获奖约 10-20 人',
        relatedMajors: ['comm', 'english', 'journalism', 'sociology'],
        relatedComps: ['john-locke', 'concord-review'],
        tags: ['写作', '免费', '多类别', '纽约时报'],
        featured: false
    },

    // ========== 科研与夏校类 ==========
    {
        id: 'sts',
        name: 'STS',
        fullName: 'Regeneron Science Talent Search',
        cnName: '再生元科学天才奖',
        category: 'research',
        difficulty: 5,
        prestige: 5,
        grades: ['12'],
        organizer: 'Society for Science',
        website: 'https://www.societyforscience.org/regeneron-science-talent-search/',
        region: 'us',
        type: 'individual',
        format: '个人 · 原创科研项目 + 申请材料',
        date: '每年 11 月提交申请，1 月公布半决赛，3 月决赛',
        fee: '免费',
        intro: '美国最古老最权威的高中生科学竞赛，面向 12 年级学生。Top 40 Finalist 可获 $25,000+，Winner 获 $250,000。',
        eligibility: '12 年级，美国公民或永久居民',
        prepTime: '需 1-2 年科研项目积累',
        awards: 'Top 300 / Top 40 Finalist / Top 10（$250,000）',
        acceptanceRate: '约 2000 人申请，Top 40 约 2%',
        relatedMajors: ['cs', 'biology', 'chemistry', 'physics', 'math'],
        relatedComps: ['isef', 'gsf'],
        tags: ['科研', '顶级', '12 年级', '美国', '免费'],
        featured: true
    },
    {
        id: 'yau-award',
        name: 'Yau Award',
        fullName: 'Shing-Tung Yau High School Science Award',
        cnName: '丘成桐中学科学奖',
        category: 'research',
        difficulty: 5,
        prestige: 5,
        grades: ['10', '11', '12'],
        organizer: '丘成桐数学科学中心',
        website: 'http://www.yau-awards.com/',
        region: 'china',
        type: 'team',
        format: '团队赛 · 科研论文 + 答辩',
        date: '每年 4-9 月提交，12 月决赛',
        fee: '免费',
        intro: '丘成桐院士发起的中学生科研竞赛，分数学、物理、化学、生物、计算机、经济金融 6 个学科。获奖可直接与顶尖学者交流。',
        eligibility: '高中生，1-3 人组队',
        prepTime: '需 6-12 个月科研',
        awards: 'Gold / Silver / Bronze / 优胜奖',
        acceptanceRate: '每年约 500 队，获奖约 30 队',
        relatedMajors: ['math', 'physics', 'cs', 'biology', 'econ'],
        relatedComps: ['isef', 'sts'],
        tags: ['科研', '顶级', '中国', '免费'],
        featured: false
    },
    {
        id: 'rsi',
        name: 'RSI',
        fullName: 'Research Science Institute',
        cnName: '科学研究暑期项目',
        category: 'summer',
        difficulty: 5,
        prestige: 5,
        grades: ['11'],
        organizer: 'CEE (Center for Excellence in Education)',
        website: 'https://www.cee.org/programs/research-science-institute',
        region: 'global',
        type: 'individual',
        format: 'MIT 暑期科研项目，6 周',
        date: '每年 6-8 月，前一年 11-1 月申请',
        fee: '免费（全额资助）',
        intro: 'MIT 主办的顶级暑期科研项目，全球约 80 名学生入选，全额资助。RSI 校友的藤校录取率极高，被称为"藤校敲门砖"。',
        eligibility: '11 年级，全球学生可申请',
        prepTime: '申请准备约 3-6 个月',
        awards: 'RSI 校友身份',
        acceptanceRate: '全球约 1600 人申请，录取约 80 人（5%）',
        relatedMajors: ['cs', 'math', 'physics', 'biology', 'engineering'],
        relatedComps: ['sts', 'isef'],
        tags: ['夏校', '顶级', 'MIT', '免费', '11 年级'],
        featured: true
    },
    {
        id: 'tasp',
        name: 'TASP',
        fullName: 'Telluride Association Summer Program',
        cnName: '特柳赖德协会暑期项目',
        category: 'summer',
        difficulty: 5,
        prestige: 5,
        grades: ['11'],
        organizer: 'Telluride Association',
        website: 'https://www.tellurideassociation.org/programs/summer-programs/',
        region: 'global',
        type: 'individual',
        format: '人文社科暑期研讨项目，6 周',
        date: '每年 6-8 月，前一年 10-1 月申请',
        fee: '免费（全额资助）',
        intro: '全免费的人文社科顶级暑期项目，录取率约 3-5%。TASP 校友在文科类申请中有极高认可度。',
        eligibility: '11 年级，全球学生可申请',
        prepTime: '申请文书准备约 2-3 个月',
        awards: 'TASP 校友身份',
        acceptanceRate: '约 1000 人申请，录取约 50-60 人（5%）',
        relatedMajors: ['philosophy', 'history', 'literature', 'sociology'],
        relatedComps: ['rsi', 'yygs'],
        tags: ['夏校', '顶级', '人文', '免费', '11 年级'],
        featured: false
    },
    {
        id: 'yygs',
        name: 'YYGS',
        fullName: 'Yale Young Global Scholars',
        cnName: '耶鲁全球青年学者',
        category: 'summer',
        difficulty: 4,
        prestige: 4,
        grades: ['10', '11'],
        organizer: 'Yale University',
        website: 'https://globalscholars.yale.edu/',
        region: 'global',
        type: 'individual',
        format: '耶鲁大学暑期学术项目，2 周',
        date: '每年 6-8 月，前一年 10-2 月申请',
        fee: '约 ¥40000（有助学金）',
        intro: '耶鲁大学主办的全球青年学者项目，提供多个学科方向。录取率约 25-30%，含金量较高但不如 RSI/TASP 顶级。',
        eligibility: '10-11 年级，全球学生',
        prepTime: '申请准备约 2 个月',
        awards: 'YYGS 结业证书',
        acceptanceRate: '约 7000 人申请，录取约 2000 人',
        relatedMajors: ['polisci', 'ir', 'econ', 'biology', 'cs'],
        relatedComps: ['rsi', 'tasp'],
        tags: ['夏校', '耶鲁', '付费', '多学科'],
        featured: false
    },
    {
        id: 'sumac',
        name: 'SUMaC',
        fullName: 'Stanford University Mathematics Camp',
        cnName: '斯坦福数学营',
        category: 'summer',
        difficulty: 5,
        prestige: 5,
        grades: ['10', '11'],
        organizer: 'Stanford University',
        website: 'https://sumac.spcs.stanford.edu/',
        region: 'global',
        type: 'individual',
        format: '斯坦福数学暑期项目，4 周',
        date: '每年 6-8 月，前一年 12-2 月申请',
        fee: '约 ¥50000（有助学金）',
        intro: '斯坦福大学主办的高难度数学暑期项目，录取率约 10%。与 PROMYS、Ross 并称三大数学营。',
        eligibility: '10-11 年级，需有扎实数学基础',
        prepTime: '申请准备约 2-3 个月',
        awards: 'SUMaC 结业证书',
        acceptanceRate: '约 600 人申请，录取约 40-60 人',
        relatedMajors: ['math', 'cs', 'physics'],
        relatedComps: ['promys', 'ross'],
        tags: ['夏校', '数学', '顶级', '斯坦福'],
        featured: false
    },
    {
        id: 'promys',
        name: 'PROMYS',
        fullName: 'Program in Mathematics for Young Scientists',
        cnName: '青年数学家项目',
        category: 'summer',
        difficulty: 5,
        prestige: 5,
        grades: ['10', '11', '12'],
        organizer: 'Boston University',
        website: 'https://www.promys.org/',
        region: 'global',
        type: 'individual',
        format: '波士顿大学数学暑期项目，6 周',
        date: '每年 7-8 月，前一年 1-3 月申请',
        fee: '约 ¥40000（有助学金）',
        intro: '波士顿大学主办的数学暑期项目，强调数论和数学证明。与 SUMaC、Ross 并称三大数学营，录取率约 15%。',
        eligibility: '10-12 年级（15 岁以上）',
        prepTime: '申请准备约 2 个月',
        awards: 'PROMYS 结业证书',
        acceptanceRate: '约 300 人申请，录取约 80 人',
        relatedMajors: ['math', 'cs', 'physics'],
        relatedComps: ['sumac', 'ross'],
        tags: ['夏校', '数学', '顶级', '波士顿'],
        featured: false
    }
];

// 竞赛分类
const CATEGORIES = [
    { id: 'math', name: 'Math & Science', cnName: '数理科学', icon: '🔬' },
    { id: 'cs', name: 'CS & Engineering', cnName: '计算机与工程', icon: '💻' },
    { id: 'business', name: 'Business & Economics', cnName: '商科与经济', icon: '📊' },
    { id: 'humanities', name: 'Humanities & Social Sciences', cnName: '人文社科', icon: '🌍' },
    { id: 'arts', name: 'Arts & Design', cnName: '艺术与设计', icon: '🎨' },
    { id: 'writing', name: 'Language & Writing', cnName: '语言与写作', icon: '✍️' },
    { id: 'research', name: 'Research & Innovation', cnName: '科研创新', icon: '⚗️' },
    { id: 'summer', name: 'Summer Programs', cnName: '暑期项目', icon: '☀️' }
];

// 专业到竞赛的映射
const MAJOR_COMPETITIONS = {
    'cs': ['usaco', 'isef', 'sts', 'gsf', 'rsi'],
    'math': ['amc', 'aime', 'usamo', 'himcm', 'sumac', 'promys'],
    'physics': ['physics-bowl', 'isef', 'sts'],
    'chemistry': ['ukcho', 'usnco'],
    'biology': ['bbo', 'usabo', 'isef'],
    'econ': ['nec', 'ieo', 'marshall-essay', 'kwhs'],
    'finance': ['kwhs', 'nec', 'fbla'],
    'business': ['fbla', 'deca', 'nec'],
    'engineering': ['vex', 'frc', 'isef'],
    'psych': ['john-locke'],
    'history': ['concord-review', 'john-locke'],
    'polisci': ['nsda', 'john-locke'],
    'arts': ['scholastic', 'youngarts'],
    'comm': ['nsda', 'nyt-contest']
};

// 导出
if (typeof window !== 'undefined') {
    window.COMPETITIONS = COMPETITIONS;
    window.COMP_CATEGORIES = CATEGORIES;
    window.MAJOR_COMPETITIONS = MAJOR_COMPETITIONS;
}
