import os
import json

# 全部课程的题目 (用列表避免引号冲突)
Q = {
"math-algebra": [
["single", "求解方程 x + 5 = 12 中 x 的值", "Solve x + 5 = 12, find the value of x", ["5", "6", "7", "8"], 2, 1],
["single", "以下哪个是一元二次方程的标准形式?", "Which is the standard form of a quadratic equation?", ["ax + b = 0", "ax^2 + bx + c = 0", "ax^3 + bx^2 + cx + d = 0", "a/x + b = 0"], 1, 1],
["judge", "0 是任何非零整数的倍数。", "Zero is a multiple of any non-zero integer.", True, 1],
["single", "函数 y = 2x + 3 的斜率是?", "What is the slope of the function y = 2x + 3?", ["2", "3", "5", "6"], 0, 1],
["single", "如果 ab = 0,那么?", "If ab = 0, then what?", ["a = 0", "b = 0", "a = 0 或 b = 0", "a = b = 0"], 2, 1],
["single", "多项式 2x^2 - 8 的因式分解结果是?", "What is the factorization of 2x^2 - 8?", ["2(x^2 - 4)", "2(x-2)(x+2)", "(2x-4)(x+2)", "2(x-2)^2"], 1, 2],
["judge", "对数函数 log(1) = 0。", "The logarithm function log(1) equals 0.", True, 1],
["single", "等差数列 1, 4, 7, 10 的公差是?", "What is the common difference of arithmetic sequence 1, 4, 7, 10?", ["1", "2", "3", "4"], 2, 1],
["single", "x^2 - 5x + 6 = 0 的两个根是?", "What are the two roots of x^2 - 5x + 6 = 0?", ["1 和 6", "2 和 3", "-2 和 -3", "1 和 5"], 1, 2],
["judge", "所有偶数都是合数。", "All even numbers are composite numbers.", False, 1],
],
"math-calc1": [
["single", "函数 f(x) = x^2 的导数是?", "What is the derivative of f(x) = x^2?", ["x", "2x", "x^2", "2"], 1, 1],
["single", "lim(x->0) sin(x)/x 等于?", "What is the limit of sin(x)/x as x approaches 0?", ["0", "1", "∞", "不存在"], 1, 1],
["judge", "导数表示函数在某点的瞬时变化率。", "Derivative represents the instantaneous rate of change.", True, 1],
["single", "∫ 2x dx = ?", "What is the integral of 2x dx?", ["x^2 + C", "2x^2 + C", "x + C", "2 + C"], 0, 1],
["single", "函数 f(x) = x^3 - 3x 的极小值点是 x = ?", "Find the minimum point of f(x) = x^3 - 3x", ["-1", "0", "1", "2"], 2, 2],
["judge", "连续函数在闭区间上一定可积。", "A continuous function is always integrable on a closed interval.", True, 1],
["single", "d/dx (e^x) = ?", "What is the derivative of e^x?", ["e^(x-1)", "e^x", "xe^(x-1)", "1/e^x"], 1, 1],
["single", "∫_0^1 x dx = ?", "What is the integral from 0 to 1 of x dx?", ["0", "1/2", "1", "2"], 1, 1],
["single", "曲线 y = x^2 在 x = 2 处的切线斜率是?", "What is the slope of tangent to y = x^2 at x = 2?", ["2", "4", "6", "8"], 1, 2],
["judge", "若 f'(x) > 0,则 f(x) 单调递增。", "If f'(x) > 0, then f(x) is monotonically increasing.", True, 1],
],
"math-calc2": [
["single", "∫_0^π sin(x) dx = ?", "What is the integral of sin(x) from 0 to pi?", ["0", "1", "2", "π"], 2, 1],
["single", "泰勒级数展开中,e^x 的展开式是?", "What is the Taylor series expansion of e^x?", ["1 + x + x^2/2! + x^3/3! + ...", "1 - x + x^2 - x^3 + ...", "x + x^3/3 + x^5/5 + ...", "1 + x + x^2 + x^3 + ..."], 0, 2],
["judge", "正项级数收敛的必要条件是其通项趋于0。", "A necessary condition for series convergence is that terms approach 0.", True, 1],
["single", "∫ x ln(x) dx = ?", "What is the integral of x ln(x) dx?", ["x^2/2 * ln(x) - x^2/4 + C", "x^2 * ln(x) + C", "ln(x) + C", "1/x + C"], 0, 2],
["single", "向量 (1,2,3) 和 (4,5,6) 的点积是?", "What is the dot product of (1,2,3) and (4,5,6)?", ["15", "32", "6", "14"], 1, 1],
["judge", "交错级数 ∑(-1)^n/n 是收敛的。", "The alternating series sum of (-1)^n/n converges.", True, 2],
["single", "∫ sec^2(x) dx = ?", "What is the integral of sec^2(x) dx?", ["sec(x) + C", "tan(x) + C", "sec(x)tan(x) + C", "ln|sec(x)| + C"], 1, 2],
["single", "y' + 2y = 0 的通解是?", "What is the general solution of y' + 2y = 0?", ["y = Ce^(2x)", "y = Ce^(-2x)", "y = 2Ce^x", "y = C/x"], 1, 2],
["judge", "幂级数的收敛半径由系数决定。", "The radius of convergence of a power series is determined by its coefficients.", True, 1],
["single", "∫_0^∞ e^(-x) dx = ?", "What is the integral from 0 to infinity of e^(-x) dx?", ["0", "1", "∞", "e"], 1, 1],
],
"math-discrete": [
["single", "集合 A = {1,2,3} 的子集有多少个?", "How many subsets does set A = {1,2,3} have?", ["3", "6", "8", "9"], 2, 1],
["single", "命题 p->q 的逆否命题是?", "What is the contrapositive of p implies q?", ["p∧q", "¬p->¬q", "¬q->¬p", "q->p"], 2, 1],
["judge", "完全图 K5 有 10 条边。", "Complete graph K5 has 10 edges.", True, 1],
["single", "5 个元素的排列数 P(5,2) 是?", "What is the permutation P(5,2)?", ["10", "20", "25", "60"], 1, 1],
["single", "C(10,3) = ?", "What is the combination C(10,3)?", ["120", "240", "720", "30"], 0, 1],
["judge", "二项式系数 C(n,k) = C(n, n-k)。", "The binomial coefficient C(n,k) equals C(n, n-k).", True, 1],
["single", "一个树有 n 个顶点,则它有?", "A tree with n vertices has how many edges?", ["n", "n-1", "n+1", "2n"], 1, 1],
["single", "欧拉回路存在的必要条件是所有顶点度数为偶数。", "A necessary condition for Euler circuit is that all vertices have even degree.", ["对", "错"], 0, 1],
["judge", "空集是任何集合的子集。", "The empty set is a subset of any set.", True, 1],
["single", "P∨¬P 等价于?", "What is P or not P equivalent to?", ["P", "¬P", "真 (Tautology)", "矛盾"], 2, 2],
],
"math-stat": [
["single", "数据 2, 4, 6, 8 的平均数是?", "What is the mean of 2, 4, 6, 8?", ["4", "5", "6", "20"], 1, 1],
["single", "标准差衡量数据的?", "What does standard deviation measure?", ["集中趋势", "离散程度", "分布形状", "中位数"], 1, 1],
["judge", "中位数不受极端值影响。", "The median is not affected by extreme values.", True, 1],
["single", "抛硬币 3 次,至少 1 次正面的概率是?", "Toss a coin 3 times, what is the probability of at least one head?", ["1/8", "3/8", "5/8", "7/8"], 3, 2],
["single", "标准正态分布的均值和方差是?", "What are the mean and variance of standard normal distribution?", ["0, 0", "0, 1", "1, 0", "1, 1"], 1, 1],
["judge", "p < 0.05 表示统计显著。", "p-value less than 0.05 indicates statistical significance.", True, 1],
["single", "一组数据中,出现次数最多的值称为?", "The most frequent value in a dataset is called?", ["平均数", "中位数", "众数", "极差"], 2, 1],
["single", "相关系数的取值范围是?", "What is the range of correlation coefficient?", ["[0, 1]", "[-1, 0]", "[-1, 1]", "[0, ∞]"], 2, 1],
["judge", "样本量越大,估计越精确。", "Larger sample size leads to more accurate estimates.", True, 1],
["single", "95% 置信区间表示?", "What does a 95% confidence interval represent?", ["参数有95%概率在此区间", "重复抽样时95%的区间会包含真值", "样本有95%在此区间", "数据有95%在此区间"], 1, 2],
],
"physics-mech": [
["single", "牛顿第二定律的公式是?", "What is the formula of Newton's second law?", ["F = ma", "F = mv", "F = mg", "F = mgh"], 0, 1],
["single", "重力加速度 g 约为?", "What is the approximate value of gravitational acceleration g?", ["9.8 m/s^2", "10.8 m/s^2", "8.9 m/s^2", "11.8 m/s^2"], 0, 1],
["judge", "动量是矢量。", "Momentum is a vector quantity.", True, 1],
["single", "匀速运动的速度是?", "What is the velocity of uniform motion?", ["零", "恒定", "随时间变化", "无法确定"], 1, 1],
["single", "1 焦耳等于?", "1 Joule equals?", ["1 N·m", "1 N/s", "1 kg·m", "1 N·m^2"], 0, 1],
["judge", "能量既不会凭空产生也不会凭空消失。", "Energy cannot be created or destroyed.", True, 1],
["single", "自由落体的加速度?", "What is the acceleration of free fall?", ["与质量有关", "g = 9.8 m/s^2", "0", "2g"], 1, 1],
["single", "向心加速度的方向是?", "What is the direction of centripetal acceleration?", ["沿速度方向", "指向圆心", "背离圆心", "竖直向上"], 1, 2],
["judge", "作用力与反作用力作用在同一物体上。", "Action and reaction forces act on the same object.", False, 2],
["single", "功率的国际单位是?", "What is the SI unit of power?", ["焦耳", "瓦特", "牛顿", "帕斯卡"], 1, 1],
],
"physics-em": [
["single", "库仑定律描述的是?", "Coulomb's law describes?", ["磁场力", "电荷间作用力", "重力", "核力"], 1, 1],
["single", "光在真空中的速度是?", "What is the speed of light in vacuum?", ["3×10^8 m/s", "3×10^6 m/s", "3×10^5 km/s", "3×10^7 m/s"], 0, 1],
["judge", "同性电荷相互吸引。", "Like charges attract each other.", False, 1],
["single", "欧姆定律是?", "What is Ohm's law?", ["V = IR", "P = IV", "F = ma", "E = mc^2"], 0, 1],
["single", "电磁感应定律的发现者是?", "Who discovered electromagnetic induction?", ["牛顿", "法拉第", "爱因斯坦", "麦克斯韦"], 1, 1],
["judge", "磁场对静止电荷有力的作用。", "Magnetic field exerts force on stationary charges.", False, 1],
["single", "电流的单位是?", "What is the unit of electric current?", ["伏特", "安培", "欧姆", "瓦特"], 1, 1],
["single", "电容器储存的是?", "What does a capacitor store?", ["电荷", "能量", "电荷和能量", "电压"], 2, 2],
["judge", "交流电的方向周期性变化。", "The direction of AC current changes periodically.", True, 1],
["single", "1 伏特等于?", "1 Volt equals?", ["1 J/C", "1 J·s", "1 C/J", "1 A·s"], 0, 2],
],
"chem-general": [
["single", "水的化学式是?", "What is the chemical formula of water?", ["H2O", "CO2", "O2", "H2O2"], 0, 1],
["single", "原子由什么组成?", "What does an atom consist of?", ["质子和电子", "质子、中子和电子", "只有质子", "只有电子"], 1, 1],
["judge", "原子序数等于质子数。", "Atomic number equals the number of protons.", True, 1],
["single", "pH = 7 表示?", "pH equals 7 indicates?", ["酸性", "碱性", "中性", "强酸"], 2, 1],
["single", "CO2 中碳的氧化态是?", "What is the oxidation state of carbon in CO2?", ["+2", "+4", "-4", "0"], 1, 2],
["judge", "化学反应遵守质量守恒定律。", "Chemical reactions obey the law of conservation of mass.", True, 1],
["single", "下列哪个是金属?", "Which of the following is a metal?", ["氧", "铁", "氮", "硫"], 1, 1],
["single", "1 摩尔包含多少个粒子?", "How many particles does 1 mole contain?", ["6.02×10^23", "6.02×10^22", "6.02×10^24", "3.14×10^23"], 0, 1],
["judge", "同位素具有相同的化学性质。", "Isotopes have the same chemical properties.", True, 1],
["single", "酸和碱反应生成?", "What do acid and base reactions produce?", ["盐和水", "氢气", "氧气", "金属"], 0, 1],
],
"chem-organic": [
["single", "甲烷的化学式是?", "What is the formula of methane?", ["CH4", "C2H6", "C3H8", "C4H10"], 0, 1],
["single", "乙醇的官能团是?", "What is the functional group of ethanol?", ["-OH", "-COOH", "-CHO", "-NH2"], 0, 1],
["judge", "所有的有机物都含碳。", "All organic compounds contain carbon.", True, 1],
["single", "苯的分子式是?", "What is the molecular formula of benzene?", ["C6H6", "C6H12", "C5H6", "C7H8"], 0, 2],
["single", "醛基的结构是?", "What is the structure of aldehyde group?", ["-CHO", "-COOH", "-OH", "-CO-"], 0, 2],
["judge", "同分异构体具有相同的分子式。", "Isomers have the same molecular formula.", True, 1],
["single", "葡萄糖属于哪类糖?", "Glucose belongs to which type of sugar?", ["多糖", "二糖", "单糖", "寡糖"], 2, 2],
["single", "下列哪个是饱和烃?", "Which of the following is a saturated hydrocarbon?", ["乙烯", "乙炔", "乙烷", "苯"], 2, 1],
["judge", "碳碳双键可以发生加成反应。", "Carbon-carbon double bonds can undergo addition reactions.", True, 1],
["single", "肥皂的主要成分属于?", "The main component of soap belongs to?", ["羧酸", "高级脂肪酸盐", "醇", "酯"], 1, 2],
],
"bio-general": [
["single", "细胞的基本结构不包括?", "Which is not a basic structure of cells?", ["细胞膜", "细胞核", "细胞壁(仅植物)", "线粒体"], 2, 1],
["single", "DNA 的中文全称是?", "What is the full Chinese name of DNA?", ["核糖核酸", "脱氧核糖核酸", "蛋白质", "氨基酸"], 1, 1],
["judge", "植物细胞有叶绿体,动物细胞没有。", "Plant cells have chloroplasts, animal cells do not.", True, 1],
["single", "光合作用的产物是?", "What are the products of photosynthesis?", ["氧气和水", "二氧化碳和水", "氧气和葡萄糖", "二氧化碳和葡萄糖"], 2, 1],
["single", "人类有染色体多少对?", "How many pairs of chromosomes do humans have?", ["22", "23", "24", "46"], 1, 1],
["judge", "细胞分裂包括有丝分裂和减数分裂。", "Cell division includes mitosis and meiosis.", True, 1],
["single", "下列哪个是单细胞生物?", "Which is a single-celled organism?", ["草履虫", "水蚤", "蚂蚁", "蚯蚓"], 0, 1],
["single", "蛋白质的基本单位是?", "What is the basic unit of protein?", ["核苷酸", "氨基酸", "脂肪酸", "葡萄糖"], 1, 1],
["judge", "酶是生物催化剂。", "Enzymes are biological catalysts.", True, 1],
["single", "下列哪个不属于生态系统成分?", "Which is not an ecosystem component?", ["生产者", "消费者", "分解者", "创造者"], 3, 1],
],
"prog-basic": [
["single", "变量是用来?", "What are variables used for?", ["存储数据", "显示图片", "连接网络", "播放音乐"], 0, 1],
["single", "以下哪个是循环语句?", "Which is a loop statement?", ["if", "for", "switch", "return"], 1, 1],
["judge", "注释会被程序执行。", "Comments are executed by the program.", False, 1],
["single", "以下哪个是布尔值?", "Which is a boolean value?", ["'hello'", "123", "true", "3.14"], 2, 1],
["single", "数组下标从几开始?", "What index does an array start from?", ["0", "1", "-1", "由程序决定"], 0, 1],
["judge", "函数可以重复使用,提高代码复用性。", "Functions can be reused, improving code reusability.", True, 1],
["single", "if (x > 5) 属于?", "What does if (x > 5) belong to?", ["循环", "条件判断", "函数", "类"], 1, 1],
["single", "Python 中定义函数的关键字是?", "What is the keyword to define a function in Python?", ["function", "def", "func", "define"], 1, 1],
["judge", "字符串可以用单引号或双引号表示。", "Strings can be represented with single or double quotes.", True, 1],
["single", "以下哪个是面向对象编程语言?", "Which is an object-oriented programming language?", ["C", "Java", "Assembly", "HTML"], 1, 1],
],
"logic-reason": [
["single", "所有 A 都是 B,C 是 A,可以推出?", "If all A are B, and C is A, what can we conclude?", ["C 是 B", "C 不是 B", "B 是 C", "无法判断"], 0, 1],
["judge", "如果前提为真,结论也必须为真,这是有效论证。", "If premises are true, conclusion must be true, this is a valid argument.", True, 1],
["single", "以下哪个是逻辑谬误?", "Which is a logical fallacy?", ["三段论", "肯定后件", "演绎推理", "归纳推理"], 1, 2],
["single", "¬(P∧Q) 等价于?", "What is not (P and Q) equivalent to?", ["¬P∧¬Q", "¬P∨¬Q", "P∨Q", "P∧Q"], 1, 2],
["judge", "充分条件是 P 蕴含 Q。", "A sufficient condition means P implies Q.", True, 1],
["single", "以下哪个是有效的三段论?", "Which is a valid syllogism?", ["所有人都会死,苏格拉底是人,所以苏格拉底会死", "所有人会死,狗会死,所以狗是人", "鸟会飞,企鹅是鸟,所以企鹅会飞", "鱼会游,蛇会游,所以蛇是鱼"], 0, 2],
["judge", "矛盾律:A 和 ¬A 不能同时为真。", "Law of contradiction: A and not A cannot both be true.", True, 1],
["single", "P∨Q 为真,P 为假,则?", "If P or Q is true, and P is false, then?", ["Q 必为真", "Q 必为假", "Q 可真可假", "P∨Q 必为假"], 0, 1],
["judge", "归纳推理从特殊到一般。", "Inductive reasoning goes from specific to general.", True, 1],
["single", "以下哪个是因果谬误?", "Which is a causal fallacy?", ["循环论证", "诉诸权威", "事后归因", "三段论"], 2, 2],
],
"digital-literacy": [
["single", "网址 http 中的 http 代表?", "What does http stand for in a URL?", ["超文本传输协议", "高级文本协议", "超链接文本协议", "主机文本协议"], 0, 1],
["single", "CPU 的中文含义是?", "What does CPU stand for in Chinese?", ["中央处理器", "计算机内存", "显示器", "硬盘"], 0, 1],
["judge", "1 KB 等于 1024 字节。", "1 KB equals 1024 bytes.", True, 1],
["single", "以下哪个是搜索引擎?", "Which is a search engine?", ["Microsoft Word", "Google", "Photoshop", "Excel"], 1, 1],
["single", "防止电脑感染病毒的有效方法是?", "What is an effective way to prevent computer viruses?", ["不联网", "安装杀毒软件", "拔掉硬盘", "关闭显示器"], 1, 1],
["judge", "强密码应包含字母、数字和符号。", "Strong passwords should contain letters, numbers, and symbols.", True, 1],
["single", "以下哪个是文件扩展名?", "Which is a file extension?", [".docx", "document", "text", "file"], 0, 1],
["single", "云存储的优点不包括?", "Which is not an advantage of cloud storage?", ["可远程访问", "需要付费", "数据备份", "多设备同步"], 1, 1],
["judge", "公开 WiFi 可能存在安全风险。", "Public WiFi may have security risks.", True, 1],
["single", "以下哪个属于办公软件?", "Which is office software?", ["Photoshop", "Microsoft Office", "Premiere", "AutoCAD"], 1, 1],
],
"eng-graphics": [
["single", "三视图不包括?", "Which is not one of the three views?", ["主视图", "俯视图", "左视图", "后视图"], 3, 1],
["single", "工程图纸中粗实线表示?", "What does a thick solid line represent in engineering drawings?", ["中心线", "可见轮廓线", "隐藏线", "辅助线"], 1, 1],
["judge", "标注尺寸以毫米为单位时,无需标注单位。", "When dimensioning in millimeters, the unit need not be marked.", True, 1],
["single", "CAD 软件主要用于?", "CAD software is mainly used for?", ["文字处理", "计算机辅助设计", "视频编辑", "音频处理"], 1, 1],
["single", "以下哪个是标准的第一角投影?", "Which is the standard first angle projection?", ["欧洲标准", "中国标准", "美国标准", "日本标准"], 1, 2],
["judge", "剖视图用于表达内部结构。", "Section views are used to show internal structures.", True, 1],
["single", "图纸幅面 A4 的尺寸是?", "What is the size of A4 drawing sheet?", ["210×297 mm", "297×420 mm", "420×594 mm", "594×841 mm"], 0, 1],
["single", "比例 1:2 表示?", "What does scale 1:2 mean?", ["图形比实物大一倍", "图形是实物的一半", "图形与实物相同", "图形是实物的两倍"], 1, 1],
["judge", "图样上的汉字应写成长仿宋体。", "Chinese characters on drawings should be in long imitation Song font.", True, 2],
["single", "尺寸标注中,R 表示?", "In dimensioning, what does R stand for?", ["直径", "半径", "角度", "弧长"], 1, 1],
],
"econ-principles": [
["single", "需求定律表明?", "The law of demand states?", ["价格上升需求上升", "价格上升需求下降", "价格与需求无关", "需求决定价格"], 1, 1],
["single", "GDP 的中文含义是?", "What does GDP stand for in Chinese?", ["国民生产总值", "国内生产总值", "国民收入", "财政收入"], 1, 1],
["judge", "供给曲线通常向右上方倾斜。", "The supply curve usually slopes upward to the right.", True, 1],
["single", "通货膨胀是指?", "Inflation refers to?", ["物价持续上涨", "物价持续下降", "货币升值", "失业增加"], 0, 1],
["single", "市场失灵的原因不包括?", "Which is not a cause of market failure?", ["外部性", "公共物品", "信息不对称", "充分竞争"], 3, 2],
["judge", "机会成本是做出选择时放弃的下一个最佳选择的价值。", "Opportunity cost is the value of the next best alternative foregone.", True, 1],
["single", "完全竞争市场的特征不包括?", "Which is not a feature of perfect competition?", ["大量买家和卖家", "产品同质", "信息完全", "产品差异化"], 3, 2],
["single", "央行提高利率通常会导致?", "When the central bank raises interest rates, it usually causes?", ["投资增加", "消费增加", "投资减少", "出口增加"], 2, 1],
["judge", "需求价格弹性衡量需求量对价格变化的敏感度。", "Price elasticity of demand measures sensitivity of quantity demanded to price changes.", True, 1],
["single", "经济学中的稀缺性指?", "Scarcity in economics refers to?", ["资源绝对缺乏", "资源相对于欲望的有限性", "资源过剩", "资源无限"], 1, 1],
],
"acct-basic": [
["single", "会计的基本职能是?", "What is the basic function of accounting?", ["记账", "反映和监督", "计算税款", "发放工资"], 1, 1],
["single", "借贷记账法中,借方表示?", "In double-entry bookkeeping, debit represents?", ["资金来源增加", "资金运用增加", "权益增加", "负债增加"], 1, 2],
["judge", "会计恒等式:资产 = 负债 + 所有者权益。", "Accounting equation: Assets = Liabilities + Owner's Equity.", True, 1],
["single", "资产负债表反映的是?", "What does a balance sheet reflect?", ["某一时期经营成果", "某一时点财务状况", "现金流入流出", "利润分配"], 1, 1],
["single", "权责发生制指?", "Accrual basis means?", ["按现金收付记账", "按经济业务发生记账", "按收付实现制记账", "按计划记账"], 1, 2],
["judge", "收入 = 费用 + 利润。", "Revenue equals expenses plus profit.", True, 1],
["single", "会计期间通常为?", "What is a typical accounting period?", ["1 个月", "1 年", "3 个月", "5 年"], 1, 1],
["single", "以下哪项属于流动资产?", "Which is a current asset?", ["房屋", "机器", "存货", "土地"], 2, 1],
["judge", "应收账款属于资产类账户。", "Accounts receivable belongs to asset accounts.", True, 1],
["single", "计提折旧属于?", "Depreciation is?", ["资产增加", "费用增加", "负债增加", "权益增加"], 1, 2],
],
"business-law": [
["single", "合同成立的基本要素不包括?", "Which is not a basic element of a contract?", ["要约", "承诺", "对价", "公正"], 3, 1],
["single", "知识产权不包括?", "Intellectual property does not include?", ["专利权", "商标权", "著作权", "财产权"], 3, 1],
["judge", "合同当事人地位平等。", "Contract parties have equal status.", True, 1],
["single", "公司是?", "A company is?", ["自然人", "法人", "合伙", "个人独资企业"], 1, 1],
["single", "商标权的保护期限通常是?", "How long is trademark protection usually?", ["5 年", "10 年", "20 年", "终身"], 1, 2],
["judge", "侵权行为需要承担民事责任。", "Tortious acts require civil liability.", True, 1],
["single", "以下哪个不是合同无效的情形?", "Which is not a case of contract invalidity?", ["违法合同", "欺诈胁迫", "意思表示真实", "恶意串通"], 2, 2],
["single", "股东大会是公司的?", "Shareholders' meeting is the company's?", ["执行机构", "权力机构", "监督机构", "管理机构"], 1, 1],
["judge", "专利分为发明、实用新型和外观设计。", "Patents are divided into invention, utility model, and design.", True, 1],
["single", "以下哪个属于商法调整对象?", "Which is a commercial law subject?", ["婚姻关系", "公司关系", "继承关系", "邻里关系"], 1, 1],
],
"info-tech": [
["single", "操作系统是?", "What is an operating system?", ["应用软件", "系统软件", "工具软件", "编程语言"], 1, 1],
["single", "IP 地址是?", "What is an IP address?", ["网卡地址", "网络协议地址", "MAC 地址", "域名"], 1, 1],
["judge", "RAM 是易失性存储器。", "RAM is volatile memory.", True, 1],
["single", "以下哪个是输入设备?", "Which is an input device?", ["显示器", "打印机", "键盘", "音箱"], 2, 1],
["single", "数据库的核心是?", "What is the core of a database?", ["数据", "表", "数据库管理系统", "视图"], 2, 1],
["judge", "防火墙可以保护网络安全。", "Firewalls can protect network security.", True, 1],
["single", "1 GB 等于?", "1 GB equals?", ["1024 KB", "1024 MB", "1000 MB", "1024 B"], 1, 1],
["single", "HTML 是?", "HTML is?", ["编程语言", "标记语言", "数据库", "操作系统"], 1, 1],
["judge", "云计算通过网络提供可伸缩的 IT 资源。", "Cloud computing provides scalable IT resources over the network.", True, 1],
["single", "以下哪个是输出设备?", "Which is an output device?", ["鼠标", "扫描仪", "显示器", "麦克风"], 2, 1],
],
"communication": [
["single", "商务沟通的第一步是?", "What is the first step in business communication?", ["倾听", "明确目标", "撰写内容", "发送信息"], 1, 1],
["single", "非语言沟通不包括?", "Non-verbal communication does not include?", ["表情", "手势", "语调", "邮件"], 3, 1],
["judge", "有效倾听是良好沟通的关键。", "Effective listening is key to good communication.", True, 1],
["single", "7C 原则中不包括?", "Which is not in the 7 C's principle?", ["清晰", "简洁", "完整", "复杂"], 3, 2],
["single", "会议主持需要?", "Meeting facilitation requires?", ["控制时间", "分配任务", "引导讨论", "以上都是"], 3, 1],
["judge", "反馈应该是具体的、建设性的。", "Feedback should be specific and constructive.", True, 1],
["single", "PPT 演示的核心是?", "What is the core of a PPT presentation?", ["精美模板", "动画效果", "清晰传达信息", "丰富文字"], 2, 1],
["single", "跨文化沟通需要?", "Cross-cultural communication requires?", ["坚持己见", "尊重差异", "回避冲突", "语言优势"], 1, 1],
["judge", "邮件标题应该简洁明确。", "Email subjects should be concise and clear.", True, 1],
["single", "演讲中最重要的是?", "What is most important in a speech?", ["发音标准", "内容逻辑", "观众互动", "服装得体"], 1, 1],
],
"lab-tech": [
["single", "实验室安全第一原则是?", "What is the first principle of lab safety?", ["穿戴防护用品", "熟悉操作规程", "保持清洁", "节约资源"], 1, 1],
["single", "量筒用于?", "A graduated cylinder is used for?", ["称量质量", "测量体积", "测量温度", "加热"], 1, 1],
["judge", "实验数据应如实记录,不可篡改。", "Experimental data should be recorded truthfully and not tampered with.", True, 1],
["single", "酒精灯使用完毕后应?", "After using an alcohol lamp, you should?", ["用嘴吹灭", "用灯帽盖灭", "直接放置", "加水冷却"], 1, 1],
["single", "滴定管读数应视线?", "When reading a burette, your eyes should be?", ["俯视", "仰视", "平视", "斜视"], 2, 1],
["judge", "实验室中禁止饮食。", "Eating and drinking are prohibited in the lab.", True, 1],
["single", "pH 试纸用于测定?", "pH paper is used to measure?", ["温度", "酸碱度", "浓度", "密度"], 1, 1],
["single", "实验中遇到事故应?", "If an accident occurs during an experiment, you should?", ["隐瞒不报", "立即报告老师", "继续实验", "自行处理"], 1, 1],
["judge", "实验结束后应清洗器具并归位。", "After the experiment, clean and return the equipment.", True, 1, 1],
["single", "电子天平读数应?", "When using an electronic balance, you should?", ["等数值稳定后读数", "立即读数", "估读", "不读数"], 0, 1],
],
"history-world": [
["single", "四大文明古国不包括?", "Which is not one of the four ancient civilizations?", ["古埃及", "古巴比伦", "古希腊", "古印度"], 2, 1],
["single", "文艺复兴起源于?", "The Renaissance originated in?", ["法国", "意大利", "英国", "德国"], 1, 1],
["judge", "哥伦布于 1492 年到达美洲。", "Columbus reached America in 1492.", True, 1],
["single", "第一次世界大战开始于?", "When did World War I begin?", ["1912", "1914", "1916", "1918"], 1, 1],
["single", "工业革命最早发生在?", "Where did the Industrial Revolution first occur?", ["美国", "法国", "英国", "德国"], 2, 1],
["judge", "二战结束于 1945 年。", "World War II ended in 1945.", True, 1],
["single", "古罗马帝国的官方语言是?", "What was the official language of the Roman Empire?", ["希腊语", "拉丁语", "意大利语", "法语"], 1, 1],
["single", "苏联解体于?", "When did the Soviet Union dissolve?", ["1989", "1991", "1993", "1995"], 1, 1],
["judge", "丝绸之路连接了东西方文明。", "The Silk Road connected Eastern and Western civilizations.", True, 1],
["single", "美国独立宣言发表于?", "When was the US Declaration of Independence issued?", ["1776", "1789", "1812", "1865"], 0, 1],
],
"research-methods": [
["single", "定量研究主要使用?", "Quantitative research mainly uses?", ["访谈", "观察", "数据统计", "文本分析"], 2, 1],
["single", "文献综述的目的是?", "What is the purpose of a literature review?", ["罗列文献", "综合分析已有研究", "批评他人", "展示自己"], 1, 1],
["judge", "研究问题应当具体、明确。", "Research questions should be specific and clear.", True, 1],
["single", "抽样方法中,最基本的是?", "What is the most basic sampling method?", ["随机抽样", "分层抽样", "系统抽样", "整群抽样"], 0, 1],
["single", "实验组和控制组的区别是?", "The difference between experimental and control group is?", ["人数不同", "是否接受实验处理", "性别不同", "年龄不同"], 1, 1],
["judge", "定性研究关注为什么而非多少。", "Qualitative research focuses on why rather than how many.", True, 1],
["single", "问卷设计应避免?", "Questionnaire design should avoid?", ["清晰问题", "引导性问题", "明确选项", "合理长度"], 1, 1],
["single", "信度衡量?", "Reliability measures?", ["准确性", "一致性", "有效性", "客观性"], 1, 2],
["judge", "样本量越大,研究结果越可靠。", "Larger sample size leads to more reliable research results.", True, 1],
["single", "研究伦理不包括?", "Research ethics does not include?", ["知情同意", "隐私保护", "数据造假", "公正性"], 2, 1],
],
"writing-academic": [
["single", "学术论文的核心结构是?", "What is the core structure of an academic paper?", ["标题、摘要、正文、参考文献", "前言、目录、结论", "封面、目录、正文", "标题、关键词、附录"], 0, 1],
["single", "摘要应包含?", "An abstract should include?", ["研究目的、方法、结果、结论", "详细内容", "所有数据", "图表"], 0, 1],
["judge", "学术写作应避免使用第一人称。", "Academic writing should avoid first person.", True, 1],
["single", "APA 引用格式主要用于?", "APA citation format is mainly used in?", ["文学", "社会科学", "自然科学", "工程技术"], 1, 2],
["single", "学术语言的特点不包括?", "Which is not a feature of academic language?", ["客观", "精确", "口语化", "严谨"], 2, 1],
["judge", "引文必须注明出处。", "Citations must be attributed.", True, 1],
["single", "文献回顾的位置通常在?", "Where is the literature review usually located?", ["引言后", "方法前", "结果后", "结论后"], 0, 1],
["single", "论文修改应关注?", "Paper revision should focus on?", ["仅错别字", "结构和逻辑", "仅格式", "仅语法"], 1, 1],
["judge", "结论部分不应引入新信息。", "The conclusion should not introduce new information.", True, 1],
["single", "引言的主要作用是?", "The main function of the introduction is?", ["罗列结果", "引出研究问题", "展示数据", "总结全文"], 1, 1],
],
"critical-thinking": [
["single", "批判性思维的核心是?", "What is the core of critical thinking?", ["盲目相信", "理性分析", "情绪判断", "直觉"], 1, 1],
["single", "以下哪个是逻辑谬误?", "Which is a logical fallacy?", ["演绎推理", "归纳推理", "稻草人谬误", "类比推理"], 2, 1],
["judge", "批判性思维意味着否定一切。", "Critical thinking means denying everything.", False, 1],
["single", "评价证据时应关注?", "When evaluating evidence, focus on?", ["来源可靠性", "数据准确性", "样本量", "以上都是"], 3, 1],
["single", "以下哪个不是论证结构?", "Which is not an argument structure?", ["前提", "结论", "假设", "修辞"], 3, 1],
["judge", "相关关系不等于因果关系。", "Correlation does not equal causation.", True, 1],
["single", "苏格拉底方法属于?", "Socratic method belongs to?", ["记忆技巧", "提问式思维", "记忆术", "填鸭式教学"], 1, 1],
["single", "避免确认偏误的方法是?", "How to avoid confirmation bias?", ["只看支持自己观点的证据", "主动寻找反证", "坚持己见", "回避不同意见"], 1, 1],
["judge", "独立思考是批判性思维的重要特征。", "Independent thinking is an important feature of critical thinking.", True, 1],
["single", "广告中常用的心理手法是?", "What psychological technique is commonly used in advertising?", ["诉诸情感", "数据呈现", "专家证言", "以上都是"], 3, 1],
],
"art-history": [
["single", "文艺复兴的核心思想是?", "What is the core idea of the Renaissance?", ["神权至上", "人文主义", "君权神授", "禁欲主义"], 1, 1],
["single", "蒙娜丽莎的作者是?", "Who is the author of Mona Lisa?", ["米开朗基罗", "达芬奇", "拉斐尔", "伦勃朗"], 1, 1],
["judge", "印象派起源于法国。", "Impressionism originated in France.", True, 1],
["single", "巴洛克艺术的特点是?", "What characterizes Baroque art?", ["简洁朴素", "华丽动感", "理性严谨", "抽象简约"], 1, 2],
["single", "现代主义艺术强调?", "Modernist art emphasizes?", ["写实", "创新和个性", "传统", "宗教主题"], 1, 1],
["judge", "中国画注重写意,西洋画注重写实。", "Chinese painting emphasizes expression, Western painting emphasizes realism.", True, 1, 1],
["single", "罗丹是著名的?", "Rodin is a famous?", ["画家", "雕塑家", "建筑师", "音乐家"], 1, 1],
["single", "梵高属于哪个流派?", "Van Gogh belongs to which school?", ["印象派", "后印象派", "立体派", "野兽派"], 1, 1],
["judge", "敦煌壁画属于佛教艺术。", "Dunhuang murals belong to Buddhist art.", True, 1],
["single", "新古典主义强调?", "Neoclassicism emphasizes?", ["情感表达", "理性与秩序", "色彩鲜艳", "抽象形式"], 1, 2],
],
"drawing-basic": [
["single", "素描的三大面是?", "What are the three main tones in sketching?", ["亮面、灰面、暗面", "上、中、下", "左、中、右", "前、中、后"], 0, 1],
["single", "透视的基本类型不包括?", "Which is not a basic type of perspective?", ["一点透视", "两点透视", "三点透视", "四点透视"], 3, 1],
["judge", "线条是素描的基础。", "Lines are the foundation of sketching.", True, 1],
["single", "明暗交界线是?", "The light-dark boundary is?", ["物体最亮处", "物体最暗处", "亮面与暗面的转折", "投影边缘"], 2, 1],
["single", "构图原则不包括?", "Composition principles do not include?", ["对比", "平衡", "重复", "随机"], 3, 1],
["judge", "速写是快速捕捉对象特征的绘画形式。", "Sketching is a drawing form that quickly captures features.", True, 1],
["single", "色彩三要素是?", "What are the three elements of color?", ["色相、明度、纯度", "红、黄、蓝", "冷、暖、中性", "光、色、形"], 0, 1],
["single", "国画用的主要颜料是?", "What are the main pigments used in Chinese painting?", ["水彩", "水粉", "国画颜料", "油画颜料"], 2, 1],
["judge", "临摹是学习绘画的有效方法。", "Copying is an effective way to learn painting.", True, 1],
["single", "近大远小是哪种透视规律?", "Near large far small is which perspective law?", ["色彩透视", "空气透视", "线性透视", "消失透视"], 2, 1],
],
"design-principles": [
["single", "平面设计四原则不包括?", "Which is not in the four principles of graphic design?", ["对比", "重复", "对齐", "堆砌"], 3, 1],
["single", "版式设计中,出血指?", "What is bleed in layout design?", ["文字颜色", "超出裁切线的部分", "图片格式", "页面大小"], 1, 2],
["judge", "好的设计应当简洁明了。", "Good design should be simple and clear.", True, 1],
["single", "网格系统的作用是?", "What is the function of a grid system?", ["美化版面", "规范版面", "增加成本", "减少可读性"], 1, 1],
["single", "品牌设计的核心是?", "What is the core of brand design?", ["标志", "色彩", "整体识别", "字体"], 2, 1],
["judge", "设计应当以人为本。", "Design should be human-centered.", True, 1],
["single", "UI 设计中的可用性指?", "What is usability in UI design?", ["美观", "易用程度", "颜色搭配", "动画效果"], 1, 1],
["single", "字体设计的目的是?", "What is the purpose of font design?", ["炫耀技巧", "传递信息", "增加难度", "装饰版面"], 1, 1],
["judge", "留白是设计的重要手法。", "White space is an important design technique.", True, 1],
["single", "Logo 设计最关键的是?", "What is most important in logo design?", ["复杂度", "辨识度", "色彩多", "字体多"], 1, 1],
],
"color-theory": [
["single", "三原色是?", "What are the three primary colors?", ["红黄蓝", "红绿蓝", "黄绿紫", "黑灰白"], 0, 1],
["single", "互补色指?", "What are complementary colors?", ["相邻颜色", "色环上相对的颜色", "相同颜色", "相似颜色"], 1, 1],
["judge", "暖色给人前进感,冷色给人后退感。", "Warm colors give a sense of advancing, cool colors give a sense of retreating.", True, 1, 1],
["single", "明度指?", "Brightness refers to?", ["颜色的鲜艳程度", "颜色的明暗", "颜色的种类", "颜色的大小"], 1, 1],
["single", "RGB 模式用于?", "RGB mode is used for?", ["印刷", "屏幕显示", "绘画", "雕塑"], 1, 1],
["judge", "色彩能影响人的情绪。", "Color can affect people's emotions.", True, 1],
["single", "CMYK 模式主要用于?", "CMYK mode is mainly used for?", ["屏幕", "印刷", "网页", "动画"], 1, 1],
["single", "饱和度指?", "Saturation refers to?", ["颜色的明亮程度", "颜色的纯度", "颜色的大小", "颜色的冷暖"], 1, 1],
["judge", "黑与白不属于色彩。", "Black and white are not considered colors.", False, 1],
["single", "以下哪个是冷色?", "Which is a cool color?", ["红", "橙", "蓝", "黄"], 2, 1],
],
"digital-tools": [
["single", "Photoshop 主要用于?", "Photoshop is mainly used for?", ["文字处理", "图像处理", "音频编辑", "视频制作"], 1, 1],
["single", "Illustrator 是?", "Illustrator is?", ["位图软件", "矢量软件", "视频软件", "音频软件"], 1, 1],
["judge", "Figma 是一款基于浏览器的协作设计工具。", "Figma is a browser-based collaborative design tool.", True, 1],
["single", "After Effects 用于?", "After Effects is used for?", ["照片处理", "动态图形和特效", "网页设计", "数据库管理"], 1, 1],
["single", "以下哪个是 3D 建模软件?", "Which is 3D modeling software?", ["Photoshop", "Blender", "Premiere", "Audition"], 1, 1],
["judge", "云端协作工具可以提高团队效率。", "Cloud collaboration tools can improve team efficiency.", True, 1],
["single", "PPT 主要用于?", "PPT is mainly used for?", ["编程", "演示文稿", "图片编辑", "财务管理"], 1, 1],
["single", "Canva 的特点是?", "What is the feature of Canva?", ["专业级图像处理", "简易的在线设计", "3D 建模", "编程开发"], 1, 1],
["judge", "短视频剪辑工具包括剪映和 CapCut。", "Short video editing tools include Jianying and CapCut.", True, 1],
["single", "设计文件常用格式是?", "What is a common design file format?", [".exe", ".psd", ".dll", ".bat"], 1, 1],
],
"psych-general": [
["single", "心理学主要研究?", "Psychology mainly studies?", ["人类行为与心理", "动物行为", "社会结构", "经济发展"], 0, 1],
["single", "弗洛伊德属于哪个流派?", "Freud belongs to which school?", ["行为主义", "精神分析", "认知心理学", "人本主义"], 1, 1],
["judge", "感觉是最简单的心理现象。", "Sensation is the simplest psychological phenomenon.", True, 1],
["single", "记忆的三个基本过程是?", "What are the three basic processes of memory?", ["编码、存储、提取", "感觉、知觉、思维", "注意、想象、情感", "动机、需要、意志"], 0, 1],
["single", "马斯洛需求层次理论最高层是?", "What is the highest level in Maslow's hierarchy?", ["生理需求", "安全需求", "尊重需求", "自我实现"], 3, 1],
["judge", "气质是个体与生俱来的心理特征。", "Temperament is an innate psychological characteristic.", True, 1],
["single", "心理学之父是?", "Who is the father of psychology?", ["弗洛伊德", "冯特", "斯金纳", "皮亚杰"], 1, 1],
["single", "情绪的基本分类不包括?", "Which is not a basic emotion category?", ["快乐", "愤怒", "悲伤", "理性"], 3, 1],
["judge", "知觉是感觉的综合。", "Perception is the synthesis of sensations.", True, 1],
["single", "IQ 100 表示?", "IQ 100 indicates?", ["智力超常", "智力中等", "智力低下", "无法判断"], 1, 1],
],
"child-dev": [
["single", "皮亚杰认知发展阶段不包括?", "Which is not a Piaget cognitive development stage?", ["感知运动阶段", "前运算阶段", "具体运算阶段", "抽象运算阶段"], 3, 1],
["single", "婴儿期是指?", "Infancy refers to?", ["0-1 岁", "0-3 岁", "1-3 岁", "3-6 岁"], 1, 1],
["judge", "依恋是婴儿与照顾者之间的情感联结。", "Attachment is the emotional bond between infant and caregiver.", True, 1],
["single", "青春期通常发生在?", "Adolescence usually occurs during?", ["8-10 岁", "10-19 岁", "20-25 岁", "25-30 岁"], 1, 1],
["single", "埃里克森理论关注?", "Erikson's theory focuses on?", ["认知发展", "社会发展", "心理社会发展", "语言发展"], 2, 2],
["judge", "游戏是儿童学习的重要方式。", "Play is an important way for children to learn.", True, 1],
["single", "语言发展关键期是?", "When is the critical period for language development?", ["0-2 岁", "2-6 岁", "6-12 岁", "12 岁后"], 0, 2],
["single", "儿童道德发展理论提出者是?", "Who proposed the theory of moral development in children?", ["皮亚杰", "科尔伯格", "维果茨基", "班杜拉"], 1, 2],
["judge", "儿童发展具有阶段性。", "Child development has stages.", True, 1],
["single", "新生儿平均体重约?", "What is the average weight of a newborn?", ["2 公斤", "3.5 公斤", "5 公斤", "6 公斤"], 1, 1],
],
"education-history": [
["single", "中国古代教育经典是?", "Which is a classic of ancient Chinese education?", ["学记", "诗经", "史记", "论语"], 0, 1],
["single", "古希腊著名教育家是?", "Who is a famous ancient Greek educator?", ["苏格拉底", "柏拉图", "亚里士多德", "以上都是"], 3, 1],
["judge", "中国古代有科举制度。", "Ancient China had the imperial examination system.", True, 1],
["single", "夸美纽斯是?", "Comenius is?", ["古代教育家", "近代教育家", "现代教育家", "当代教育家"], 1, 1],
["single", "杜威提出?", "Dewey proposed?", ["传统教育", "进步主义教育", "永恒主义教育", "要素主义教育"], 1, 2],
["judge", "赫尔巴特被誉为现代教育学之父。", "Herbart is called the father of modern pedagogy.", True, 1],
["single", "我国近代第一所师范学校是?", "What is the first normal school in modern China?", ["京师大学堂", "南洋公学师范院", "北大", "清华"], 1, 2],
["single", "孔子提倡?", "Confucius advocated?", ["有教无类", "因材施教", "温故知新", "以上都是"], 3, 1],
["judge", "素质教育强调全面发展。", "Quality education emphasizes all-round development.", True, 1],
["single", "现代教育的重要特征是?", "What is an important feature of modern education?", ["面向少数人", "普及化", "脱离生活", "重视记忆"], 1, 1],
],
"learning-theory": [
["single", "行为主义的代表是?", "Who represents behaviorism?", ["斯金纳", "弗洛伊德", "皮亚杰", "马斯洛"], 0, 1],
["single", "强化理论属于?", "Reinforcement theory belongs to?", ["行为主义", "认知主义", "建构主义", "人本主义"], 0, 1],
["judge", "建构主义强调学习者的主动性。", "Constructivism emphasizes learner initiative.", True, 1],
["single", "认知主义关注?", "Cognitivism focuses on?", ["外部刺激", "内部心理过程", "无意识", "生理反应"], 1, 1],
["single", "观察学习的提出者是?", "Who proposed observational learning?", ["班杜拉", "斯金纳", "皮亚杰", "维果茨基"], 0, 1],
["judge", "有意义学习是新知识与已有知识建立联系。", "Meaningful learning connects new knowledge with existing knowledge.", True, 1],
["single", "最近发展区的提出者是?", "Who proposed the zone of proximal development?", ["皮亚杰", "维果茨基", "布鲁纳", "奥苏贝尔"], 1, 2],
["single", "正强化是?", "Positive reinforcement is?", ["施加厌恶刺激", "给予愉快刺激", "取消愉快刺激", "无刺激"], 1, 1],
["judge", "学习风格影响学习效果。", "Learning style affects learning outcomes.", True, 1],
["single", "元认知是?", "Metacognition is?", ["对学习的认识", "对认知的认知", "对记忆的认识", "对情感的认识"], 1, 2],
],
"classroom-mgmt": [
["single", "课堂管理的核心目标是?", "What is the core goal of classroom management?", ["控制学生", "营造良好学习环境", "惩罚违纪", "完成教学任务"], 1, 1],
["single", "制定课堂规则应在?", "When should classroom rules be set?", ["学期末", "学期初", "出现问题时", "随意"], 1, 1],
["judge", "积极倾听能促进师生关系。", "Active listening promotes teacher-student relationships.", True, 1],
["single", "处理学生违纪行为应?", "How should student misbehavior be handled?", ["立即严厉批评", "了解情况后处理", "当众羞辱", "置之不理"], 1, 1],
["single", "课堂提问应?", "Classroom questions should?", ["只问好学生", "面向全体学生", "难度统一", "不需要等待"], 1, 1],
["judge", "良好的课堂氛围能提高学习效果。", "A positive classroom atmosphere improves learning.", True, 1],
["single", "时间管理是课堂管理的?", "Time management is?", ["可选技能", "重要组成部分", "与教学无关", "浪费时间"], 1, 1],
["single", "表扬学生应?", "Praising students should be?", ["泛泛而谈", "具体真诚", "千篇一律", "随意"], 1, 1],
["judge", "差异化教学是课堂管理的重要策略。", "Differentiated instruction is an important classroom management strategy.", True, 1],
["single", "应对突发事件应?", "How to handle unexpected events?", ["惊慌失措", "冷静处理", "假装没看见", "大声训斥"], 1, 1],
],
"diversity": [
["single", "多元文化教育的核心是?", "What is the core of multicultural education?", ["文化同化", "尊重文化差异", "文化隔离", "文化优越"], 1, 1],
["single", "文化敏感性指?", "Cultural sensitivity refers to?", ["对文化差异的察觉", "对所有文化的认同", "文化优越感", "文化排斥"], 0, 1],
["judge", "多元文化教育促进社会公平。", "Multicultural education promotes social equity.", True, 1],
["single", "双语教学有利于?", "Bilingual teaching is beneficial for?", ["语言发展", "文化理解", "认知发展", "以上都是"], 3, 1],
["single", "教师应避免?", "Teachers should avoid?", ["文化偏见", "文化包容", "文化尊重", "多元视角"], 0, 1],
["judge", "每个学生都应得到公平的教育机会。", "Every student should have equal educational opportunities.", True, 1],
["single", "文化回应式教学强调?", "Culturally responsive teaching emphasizes?", ["忽视文化", "利用学生文化背景", "统一教学", "填鸭式教学"], 1, 1],
["single", "学校应?", "Schools should?", ["排斥少数族裔", "包容多元文化", "强制同化", "区分对待"], 1, 1],
["judge", "刻板印象会影响教育公平。", "Stereotypes affect educational equity.", True, 1],
["single", "全球公民教育旨在?", "Global citizenship education aims to?", ["强化民族主义", "培养国际视野", "排斥外来文化", "文化孤立"], 1, 1],
],
}

COURSE_NAMES = {
"math-algebra": "代数基础", "math-calc1": "微积分I", "math-calc2": "微积分II",
"math-discrete": "离散数学入门", "math-stat": "统计学入门",
"physics-mech": "力学基础", "physics-em": "电磁学",
"chem-general": "普通化学", "chem-organic": "有机化学入门",
"bio-general": "普通生物学", "prog-basic": "编程入门",
"logic-reason": "逻辑推理", "digital-literacy": "数字素养",
"eng-graphics": "工程制图", "econ-principles": "经济学原理",
"acct-basic": "会计学基础", "business-law": "商法入门",
"info-tech": "信息技术基础", "communication": "商务沟通",
"lab-tech": "实验室技术", "history-world": "世界历史",
"research-methods": "研究方法", "writing-academic": "学术写作",
"critical-thinking": "批判性思维", "art-history": "艺术史",
"drawing-basic": "绘画基础", "design-principles": "设计原理",
"color-theory": "色彩理论", "digital-tools": "数字工具",
"psych-general": "普通心理学", "child-dev": "儿童发展",
"education-history": "教育史", "learning-theory": "学习理论",
"classroom-mgmt": "课堂管理", "diversity": "多元文化教育",
}

def main():
    questions = []
    for course_id, qs in Q.items():
        course_name = COURSE_NAMES.get(course_id, course_id)
        for idx, q in enumerate(qs):
            # q: [type, q_cn, q_en, options, answer, diff?]
            qtype = q[0]
            qtext = q[1]
            qen = q[2]
            opts = q[3]
            ans = q[4]
            diff = q[5] if len(q) > 5 else 1
            questions.append({
                "id": f"{course_id}-{idx+1:03d}",
                "courseId": course_id,
                "courseName": course_name,
                "type": qtype,
                "question": qtext,
                "questionEn": qen,
                "options": opts,
                "answer": ans,
                "explanation": "",
                "difficulty": diff
            })
    os.makedirs("/workspace/prerequisite/quiz/data", exist_ok=True)
    with open("/workspace/prerequisite/quiz/data/questions.json", "w", encoding="utf-8") as f:
        json.dump(questions, f, ensure_ascii=False, indent=2)
    print(f"生成题目: {len(questions)} 道")
    print(f"覆盖课程: {len(Q)} 门")

if __name__ == "__main__":
    main()
