import os
import re

# 全部课程的题目模板（每门课至少10题）
# 中文题干 + 英文题干（用于朗读英文时使用）
QUESTIONS_DATA = {
    "math-algebra": [
        {"type": "single", 'q': '代数中，求解方程 x + 5 = 12 中 x 的值', "qEn": "Solve x + 5 = 12, find the value of x", "options": ["5", "6", "7", "8"], "answer": 2, "diff": 1},
        {"type": "single", 'q': '以下哪个是一元二次方程的标准形式？', "qEn": "Which is the standard form of a quadratic equation?", "options": ["ax + b = 0", "ax² + bx + c = 0", "ax³ + bx² + cx + d = 0", "a/x + b = 0"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '0 是任何非零整数的倍数。', "qEn": "Zero is a multiple of any non-zero integer.", "answer": True, "diff": 1},
        {"type": "single", 'q': '函数 y = 2x + 3 的斜率是？', "qEn": "What is the slope of the function y = 2x + 3?", "options": ["2", "3", "5", "6"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '如果 ab = 0，那么？', "qEn": "If ab = 0, then what?", "options": ["a = 0", "b = 0", "a = 0 或 b = 0", "a = b = 0"], "answer": 2, "diff": 1},
        {"type": "single", 'q': '多项式 2x² - 8 的因式分解结果是？', "qEn": "What is the factorization of 2x² - 8?", "options": ["2(x² - 4)", "2(x-2)(x+2)", "(2x-4)(x+2)", "2(x-2)²"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '对数函数 log(1) = 0。', "qEn": "The logarithm function log(1) equals 0.", "answer": True, "diff": 1},
        {"type": "single", 'q': '等差数列 1, 4, 7, 10 的公差是？', "qEn": "What is the common difference of arithmetic sequence 1, 4, 7, 10?", "options": ["1", "2", "3", "4"], "answer": 2, "diff": 1},
        {"type": "single", 'q': 'x² - 5x + 6 = 0 的两个根是？', "qEn": "What are the two roots of x² - 5x + 6 = 0?", "options": ["1 和 6", "2 和 3", "-2 和 -3", "1 和 5"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '所有偶数都是合数。', "qEn": "All even numbers are composite numbers.", "answer": False, "diff": 1},
    ],
    "math-calc1": [
        {"type": "single", 'q': '函数 f(x) = x² 的导数是？', "qEn": "What is the derivative of f(x) = x²?", "options": ["x", "2x", "x²", "2"], "answer": 1, "diff": 1},
        {"type": "single", 'q': 'lim(x→0) sin(x)/x 等于？', "qEn": "What is the limit of sin(x)/x as x approaches 0?", "options": ["0", "1", "∞", "不存在"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '导数表示函数在某点的瞬时变化率。', "qEn": "Derivative represents the instantaneous rate of change.", "answer": True, "diff": 1},
        {"type": "single", 'q': '∫ 2x dx = ?', "qEn": "What is the integral of 2x dx?", "options": ["x² + C", "2x² + C", "x + C", "2 + C"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '函数 f(x) = x³ - 3x 的极小值点是 x = ?', "qEn": "Find the minimum point of f(x) = x³ - 3x", "options": ["-1", "0", "1", "2"], "answer": 2, "diff": 2},
        {"type": "judge", 'q': '连续函数在闭区间上一定可积。', "qEn": "A continuous function is always integrable on a closed interval.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'd/dx (e^x) = ?', "qEn": "What is the derivative of e^x?", "options": ["e^(x-1)", "e^x", "xe^(x-1)", "1/e^x"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '∫₀¹ x dx = ?', "qEn": "What is the integral from 0 to 1 of x dx?", "options": ["0", "1/2", "1", "2"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '曲线 y = x² 在 x = 2 处的切线斜率是？', "qEn": "What is the slope of tangent to y = x² at x = 2?", "options": ["2", "4", "6", "8"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '若 f'(x) > 0，则 f(x) 单调递增。', "qEn": "If f'(x) > 0, then f(x) is monotonically increasing.", "answer": True, "diff": 1},
    ],
    "math-calc2": [
        {"type": "single", 'q': '∫₀^π sin(x) dx = ?', "qEn": "What is the integral of sin(x) from 0 to pi?", "options": ["0", "1", "2", "π"], "answer": 2, "diff": 1},
        {"type": "single", 'q': '泰勒级数展开中，e^x 的展开式是？', "qEn": "What is the Taylor series expansion of e^x?", "options": ["1 + x + x²/2! + x³/3! + ...", "1 - x + x² - x³ + ...", "x + x³/3 + x⁵/5 + ...", "1 + x + x² + x³ + ..."], "answer": 0, "diff": 2},
        {"type": "judge", 'q': '正项级数收敛的必要条件是其通项趋于0。', "qEn": "A necessary condition for series convergence is that terms approach 0.", "answer": True, "diff": 1},
        {"type": "single", 'q': '∫ x ln(x) dx = ?', "qEn": "What is the integral of x ln(x) dx?", "options": ["x²/2 · ln(x) - x²/4 + C", "x² · ln(x) + C", "ln(x) + C", "1/x + C"], "answer": 0, "diff": 2},
        {"type": "single", 'q': '向量 (1,2,3) 和 (4,5,6) 的点积是？', "qEn": "What is the dot product of (1,2,3) and (4,5,6)?", "options": ["15", "32", "6", "14"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '交错级数 ∑(-1)^n/n 是收敛的。', "qEn": "The alternating series sum of (-1)^n/n converges.", "answer": True, "diff": 2},
        {"type": "single", 'q': '∫ sec²(x) dx = ?', "qEn": "What is the integral of sec²(x) dx?", "options": ["sec(x) + C", "tan(x) + C", "sec(x)tan(x) + C", "ln|sec(x)| + C"], "answer": 1, "diff": 2},
        {"type": "single", 'q': 'y' + 2y = 0 的通解是？', "qEn": "What is the general solution of y' + 2y = 0?", "options": ["y = Ce^(2x)", "y = Ce^(-2x)", "y = 2Ce^x", "y = C/x"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '幂级数的收敛半径由系数决定。', "qEn": "The radius of convergence of a power series is determined by its coefficients.", "answer": True, "diff": 1},
        {"type": "single", 'q': '∫₀^∞ e^(-x) dx = ?', "qEn": "What is the integral from 0 to infinity of e^(-x) dx?", "options": ["0", "1", "∞", "e"], "answer": 1, "diff": 1},
    ],
    "math-discrete": [
        {"type": "single", 'q': '集合 A = {1,2,3} 的子集有多少个？', "qEn": "How many subsets does set A = {1,2,3} have?", "options": ["3", "6", "8", "9"], "answer": 2, "diff": 1},
        {"type": "single", 'q': '命题 p→q 的逆否命题是？', "qEn": "What is the contrapositive of p implies q?", "options": ["p∧q", "¬p→¬q", "¬q→¬p", "q→p"], "answer": 2, "diff": 1},
        {"type": "judge", 'q': '完全图 K₅ 有 10 条边。', "qEn": "Complete graph K5 has 10 edges.", "answer": True, "diff": 1},
        {"type": "single", 'q': '5 个元素的排列数 P(5,2) 是？', "qEn": "What is the permutation P(5,2)?", "options": ["10", "20", "25", "60"], "answer": 1, "diff": 1},
        {"type": "single", 'q': 'C(10,3) = ?', "qEn": "What is the combination C(10,3)?", "options": ["120", "240", "720", "30"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '二项式系数 C(n,k) = C(n, n-k)。', "qEn": "The binomial coefficient C(n,k) equals C(n, n-k).", "answer": True, "diff": 1},
        {"type": "single", 'q': '一个树有 n 个顶点，则它有？', "qEn": "A tree with n vertices has how many edges?", "options": ["n", "n-1", "n+1", "2n"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '欧拉回路存在的必要条件是所有顶点度数为偶数。', "qEn": "A necessary condition for Euler circuit is that all vertices have even degree.", "options": ["对", "错"], "answer": 0, "diff": 1, "options_real": ["True", "False"]},
        {"type": "judge", 'q': '空集是任何集合的子集。', "qEn": "The empty set is a subset of any set.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'P∨¬P 等价于？', "qEn": "What is P or not P equivalent to?", "options": ["P", "¬P", "真（Tautology）", "矛盾"], "answer": 2, "diff": 2},
    ],
    "math-stat": [
        {"type": "single", 'q': '数据 2, 4, 6, 8 的平均数是？', "qEn": "What is the mean of 2, 4, 6, 8?", "options": ["4", "5", "6", "20"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '标准差衡量数据的？', "qEn": "What does standard deviation measure?", "options": ["集中趋势", "离散程度", "分布形状", "中位数"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '中位数不受极端值影响。', "qEn": "The median is not affected by extreme values.", "answer": True, "diff": 1},
        {"type": "single", 'q': '抛硬币 3 次，至少 1 次正面的概率是？', "qEn": "Toss a coin 3 times, what is the probability of at least one head?", "options": ["1/8", "3/8", "5/8", "7/8"], "answer": 3, "diff": 2},
        {"type": "single", 'q': '标准正态分布的均值和方差是？', "qEn": "What are the mean and variance of standard normal distribution?", "options": ["0, 0", "0, 1", "1, 0", "1, 1"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': 'p < 0.05 表示统计显著。', "qEn": "p-value less than 0.05 indicates statistical significance.", "answer": True, "diff": 1},
        {"type": "single", 'q': '一组数据中，出现次数最多的值称为？', "qEn": "The most frequent value in a dataset is called?", "options": ["平均数", "中位数", "众数", "极差"], "answer": 2, "diff": 1},
        {"type": "single", 'q': '相关系数的取值范围是？', "qEn": "What is the range of correlation coefficient?", "options": ["[0, 1]", "[-1, 0]", "[-1, 1]", "[0, ∞]"], "answer": 2, "diff": 1},
        {"type": "judge", 'q': '样本量越大，估计越精确。', "qEn": "Larger sample size leads to more accurate estimates.", "answer": True, "diff": 1},
        {"type": "single", 'q': '95% 置信区间表示？', "qEn": "What does a 95% confidence interval represent?", "options": ["参数有95%概率在此区间", "重复抽样时95%的区间会包含真值", "样本有95%在此区间", "数据有95%在此区间"], "answer": 1, "diff": 2},
    ],
    "physics-mech": [
        {"type": "single", 'q': '牛顿第二定律的公式是？', "qEn": "What is the formula of Newton's second law?", "options": ["F = ma", "F = mv", "F = mg", "F = mgh"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '重力加速度 g 约为？', "qEn": "What is the approximate value of gravitational acceleration g?", "options": ["9.8 m/s²", "10.8 m/s²", "8.9 m/s²", "11.8 m/s²"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '动量是矢量。', "qEn": "Momentum is a vector quantity.", "answer": True, "diff": 1},
        {"type": "single", 'q': '匀速运动的速度是？', "qEn": "What is the velocity of uniform motion?", "options": ["零", "恒定", "随时间变化", "无法确定"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '1 焦耳等于？', "qEn": "1 Joule equals?", "options": ["1 N·m", "1 N/s", "1 kg·m", "1 N·m²"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '能量既不会凭空产生也不会凭空消失。', "qEn": "Energy cannot be created or destroyed.", "answer": True, "diff": 1},
        {"type": "single", 'q': '自由落体的加速度？', "qEn": "What is the acceleration of free fall?", "options": ["与质量有关", "g = 9.8 m/s²", "0", "2g"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '向心加速度的方向是？', "qEn": "What is the direction of centripetal acceleration?", "options": ["沿速度方向", "指向圆心", "背离圆心", "竖直向上"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '作用力与反作用力作用在同一物体上。', "qEn": "Action and reaction forces act on the same object.", "answer": False, "diff": 2},
        {"type": "single", 'q': '功率的国际单位是？', "qEn": "What is the SI unit of power?", "options": ["焦耳", "瓦特", "牛顿", "帕斯卡"], "answer": 1, "diff": 1},
    ],
    "physics-em": [
        {"type": "single", 'q': '库仑定律描述的是？', "qEn": "Coulomb's law describes?", "options": ["磁场力", "电荷间作用力", "重力", "核力"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '光在真空中的速度是？', "qEn": "What is the speed of light in vacuum?", "options": ["3×10⁸ m/s", "3×10⁶ m/s", "3×10⁵ km/s", "3×10⁷ m/s"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '同性电荷相互吸引。', "qEn": "Like charges attract each other.", "answer": False, "diff": 1},
        {"type": "single", 'q': '欧姆定律是？', "qEn": "What is Ohm's law?", "options": ["V = IR", "P = IV", "F = ma", "E = mc²"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '电磁感应定律的发现者是？', "qEn": "Who discovered electromagnetic induction?", "options": ["牛顿", "法拉第", "爱因斯坦", "麦克斯韦"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '磁场对静止电荷有力的作用。', "qEn": "Magnetic field exerts force on stationary charges.", "answer": False, "diff": 1},
        {"type": "single", 'q': '电流的单位是？', "qEn": "What is the unit of electric current?", "options": ["伏特", "安培", "欧姆", "瓦特"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '电容器储存的是？', "qEn": "What does a capacitor store?", "options": ["电荷", "能量", "电荷和能量", "电压"], "answer": 2, "diff": 2},
        {"type": "judge", 'q': '交流电的方向周期性变化。', "qEn": "The direction of AC current changes periodically.", "answer": True, "diff": 1},
        {"type": "single", 'q': '1 伏特等于？', "qEn": "1 Volt equals?", "options": ["1 J/C", "1 J·s", "1 C/J", "1 A·s"], "answer": 0, "diff": 2},
    ],
    "chem-general": [
        {"type": "single", 'q': '水的化学式是？', "qEn": "What is the chemical formula of water?", "options": ["H₂O", "CO₂", "O₂", "H₂O₂"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '原子由什么组成？', "qEn": "What does an atom consist of?", "options": ["质子和电子", "质子、中子和电子", "只有质子", "只有电子"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '原子序数等于质子数。', "qEn": "Atomic number equals the number of protons.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'pH = 7 表示？', "qEn": "pH equals 7 indicates?", "options": ["酸性", "碱性", "中性", "强酸"], "answer": 2, "diff": 1},
        {"type": "single", 'q': 'CO₂ 中碳的氧化态是？', "qEn": "What is the oxidation state of carbon in CO₂?", "options": ["+2", "+4", "-4", "0"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '化学反应遵守质量守恒定律。', "qEn": "Chemical reactions obey the law of conservation of mass.", "answer": True, "diff": 1},
        {"type": "single", 'q': '下列哪个是金属？', "qEn": "Which of the following is a metal?", "options": ["氧", "铁", "氮", "硫"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '1 摩尔包含多少个粒子？', "qEn": "How many particles does 1 mole contain?", "options": ["6.02×10²³", "6.02×10²²", "6.02×10²⁴", "3.14×10²³"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '同位素具有相同的化学性质。', "qEn": "Isotopes have the same chemical properties.", "answer": True, "diff": 1},
        {"type": "single", 'q': '酸和碱反应生成？', "qEn": "What do acid and base reactions produce?", "options": ["盐和水", "氢气", "氧气", "金属"], "answer": 0, "diff": 1},
    ],
    "chem-organic": [
        {"type": "single", 'q': '甲烷的化学式是？', "qEn": "What is the formula of methane?", "options": ["CH₄", "C₂H₆", "C₃H₈", "C₄H₁₀"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '乙醇的官能团是？', "qEn": "What is the functional group of ethanol?", "options": ["-OH", "-COOH", "-CHO", "-NH₂"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '所有的有机物都含碳。', "qEn": "All organic compounds contain carbon.", "answer": True, "diff": 1},
        {"type": "single", 'q': '苯的分子式是？', "qEn": "What is the molecular formula of benzene?", "options": ["C₆H₆", "C₆H₁₂", "C₅H₆", "C₇H₈"], "answer": 0, "diff": 2},
        {"type": "single", 'q': '醛基的结构是？', "qEn": "What is the structure of aldehyde group?", "options": ["-CHO", "-COOH", "-OH", "-CO-"], "answer": 0, "diff": 2},
        {"type": "judge", 'q': '同分异构体具有相同的分子式。', "qEn": "Isomers have the same molecular formula.", "answer": True, "diff": 1},
        {"type": "single", 'q': '葡萄糖属于哪类糖？', "qEn": "Glucose belongs to which type of sugar?", "options": ["多糖", "二糖", "单糖", "寡糖"], "answer": 2, "diff": 2},
        {"type": "single", 'q': '下列哪个是饱和烃？', "qEn": "Which of the following is a saturated hydrocarbon?", "options": ["乙烯", "乙炔", "乙烷", "苯"], "answer": 2, "diff": 1},
        {"type": "judge", 'q': '碳碳双键可以发生加成反应。', "qEn": "Carbon-carbon double bonds can undergo addition reactions.", "answer": True, "diff": 1},
        {"type": "single", 'q': '肥皂的主要成分属于？', "qEn": "The main component of soap belongs to?", "options": ["羧酸", "高级脂肪酸盐", "醇", "酯"], "answer": 1, "diff": 2},
    ],
    "bio-general": [
        {"type": "single", 'q': '细胞的基本结构不包括？', "qEn": "Which is not a basic structure of cells?", "options": ["细胞膜", "细胞核", "细胞壁（仅植物）", "线粒体"], "answer": 2, "diff": 1},
        {"type": "single", 'q': 'DNA 的中文全称是？', "qEn": "What is the full Chinese name of DNA?", "options": ["核糖核酸", "脱氧核糖核酸", "蛋白质", "氨基酸"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '植物细胞有叶绿体，动物细胞没有。', "qEn": "Plant cells have chloroplasts, animal cells do not.", "answer": True, "diff": 1},
        {"type": "single", 'q': '光合作用的产物是？', "qEn": "What are the products of photosynthesis?", "options": ["氧气和水", "二氧化碳和水", "氧气和葡萄糖", "二氧化碳和葡萄糖"], "answer": 2, "diff": 1},
        {"type": "single", 'q': '人类有染色体多少对？', "qEn": "How many pairs of chromosomes do humans have?", "options": ["22", "23", "24", "46"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '细胞分裂包括有丝分裂和减数分裂。', "qEn": "Cell division includes mitosis and meiosis.", "answer": True, "diff": 1},
        {"type": "single", 'q': '下列哪个是单细胞生物？', "qEn": "Which is a single-celled organism?", "options": ["草履虫", "水蚤", "蚂蚁", "蚯蚓"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '蛋白质的基本单位是？', "qEn": "What is the basic unit of protein?", "options": ["核苷酸", "氨基酸", "脂肪酸", "葡萄糖"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '酶是生物催化剂。', "qEn": "Enzymes are biological catalysts.", "answer": True, "diff": 1},
        {"type": "single", 'q': '下列哪个不属于生态系统成分？', "qEn": "Which is not an ecosystem component?", "options": ["生产者", "消费者", "分解者", "创造者"], "answer": 3, "diff": 1},
    ],
    "prog-basic": [
        {"type": "single", 'q': '变量是用来？', "qEn": "What are variables used for?", "options": ["存储数据", "显示图片", "连接网络", "播放音乐"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '以下哪个是循环语句？', "qEn": "Which is a loop statement?", "options": ["if", "for", "switch", "return"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '注释会被程序执行。', "qEn": "Comments are executed by the program.", "answer": False, "diff": 1},
        {"type": "single", 'q': '以下哪个是布尔值？', "qEn": "Which is a boolean value?", "options": ["'hello'", "123", "true", "3.14"], "answer": 2, "diff": 1},
        {"type": "single", 'q': '数组下标从几开始？', "qEn": "What index does an array start from?", "options": ["0", "1", "-1", "由程序决定"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '函数可以重复使用，提高代码复用性。', "qEn": "Functions can be reused, improving code reusability.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'if (x > 5) 属于？', "qEn": "What does if (x > 5) belong to?", "options": ["循环", "条件判断", "函数", "类"], "answer": 1, "diff": 1},
        {"type": "single", 'q': 'Python 中定义函数的关键字是？', "qEn": "What is the keyword to define a function in Python?", "options": ["function", "def", "func", "define"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '字符串可以用单引号或双引号表示。', "qEn": "Strings can be represented with single or double quotes.", "answer": True, "diff": 1},
        {"type": "single", 'q': '以下哪个是面向对象编程语言？', "qEn": "Which is an object-oriented programming language?", "options": ["C", "Java", "Assembly", "HTML"], "answer": 1, "diff": 1},
    ],
    "logic-reason": [
        {"type": "single", 'q': '所有 A 都是 B，C 是 A，可以推出？', "qEn": "If all A are B, and C is A, what can we conclude?", "options": ["C 是 B", "C 不是 B", "B 是 C", "无法判断"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '如果前提为真，结论也必须为真，这是有效论证。', "qEn": "If premises are true, conclusion must be true, this is a valid argument.", "answer": True, "diff": 1},
        {"type": "single", 'q': '以下哪个是逻辑谬误？', "qEn": "Which is a logical fallacy?", "options": ["三段论", "肯定后件", "演绎推理", "归纳推理"], "answer": 1, "diff": 2},
        {"type": "single", 'q': '¬(P∧Q) 等价于？', "qEn": "What is not (P and Q) equivalent to?", "options": ["¬P∧¬Q", "¬P∨¬Q", "P∨Q", "P∧Q"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '充分条件是 P 蕴含 Q。', "qEn": "A sufficient condition means P implies Q.", "answer": True, "diff": 1},
        {"type": "single", 'q': '以下哪个是有效的三段论？', "qEn": "Which is a valid syllogism?", "options": ["所有人都会死，苏格拉底是人，所以苏格拉底会死", "所有人会死，狗会死，所以狗是人", "鸟会飞，企鹅是鸟，所以企鹅会飞", "鱼会游，蛇会游，所以蛇是鱼"], "answer": 0, "diff": 2},
        {"type": "judge", 'q': '矛盾律：A 和 ¬A 不能同时为真。', "qEn": "Law of contradiction: A and not A cannot both be true.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'P∨Q 为真，P 为假，则？', "qEn": "If P or Q is true, and P is false, then?", "options": ["Q 必为真", "Q 必为假", "Q 可真可假", "P∨Q 必为假"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '归纳推理从特殊到一般。', "qEn": "Inductive reasoning goes from specific to general.", "answer": True, "diff": 1},
        {"type": "single", 'q': '以下哪个是因果谬误？', "qEn": "Which is a causal fallacy?", "options": ["循环论证", "诉诸权威", "事后归因", "三段论"], "answer": 2, "diff": 2},
    ],
    "digital-literacy": [
        {"type": "single", 'q': '网址 http 中的 http 代表？', "qEn": "What does http stand for in a URL?", "options": ["超文本传输协议", "高级文本协议", "超链接文本协议", "主机文本协议"], "answer": 0, "diff": 1},
        {"type": "single", 'q': 'CPU 的中文含义是？', "qEn": "What does CPU stand for in Chinese?", "options": ["中央处理器", "计算机内存", "显示器", "硬盘"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '1 KB 等于 1024 字节。', "qEn": "1 KB equals 1024 bytes.", "answer": True, "diff": 1},
        {"type": "single", 'q': '以下哪个是搜索引擎？', "qEn": "Which is a search engine?", "options": ["Microsoft Word", "Google", "Photoshop", "Excel"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '防止电脑感染病毒的有效方法是？', "qEn": "What is an effective way to prevent computer viruses?", "options": ["不联网", "安装杀毒软件", "拔掉硬盘", "关闭显示器"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '强密码应包含字母、数字和符号。', "qEn": "Strong passwords should contain letters, numbers, and symbols.", "answer": True, "diff": 1},
        {"type": "single", 'q': '以下哪个是文件扩展名？', "qEn": "Which is a file extension?", "options": [".docx", "document", "text", "file"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '云存储的优点不包括？', "qEn": "Which is not an advantage of cloud storage?", "options": ["可远程访问", "需要付费", "数据备份", "多设备同步"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '公开 WiFi 可能存在安全风险。', "qEn": "Public WiFi may have security risks.", "answer": True, "diff": 1},
        {"type": "single", 'q': '以下哪个属于办公软件？', "qEn": "Which is office software?", "options": ["Photoshop", "Microsoft Office", "Premiere", "AutoCAD"], "answer": 1, "diff": 1},
    ],
    "eng-graphics": [
        {"type": "single", 'q': '三视图不包括？', "qEn": "Which is not one of the three views?", "options": ["主视图", "俯视图", "左视图", "后视图"], "answer": 3, "diff": 1},
        {"type": "single", 'q': '工程图纸中粗实线表示？', "qEn": "What does a thick solid line represent in engineering drawings?", "options": ["中心线", "可见轮廓线", "隐藏线", "辅助线"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '标注尺寸以毫米为单位时，无需标注单位。', "qEn": "When dimensioning in millimeters, the unit need not be marked.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'CAD 软件主要用于？', "qEn": "CAD software is mainly used for?", "options": ["文字处理", "计算机辅助设计", "视频编辑", "音频处理"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '以下哪个是标准的第一角投影？', "qEn": "Which is the standard first angle projection?", "options": ["欧洲标准", "中国标准", "美国标准", "日本标准"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '剖视图用于表达内部结构。', "qEn": "Section views are used to show internal structures.", "answer": True, "diff": 1},
        {"type": "single", 'q': '图纸幅面 A4 的尺寸是？', "qEn": "What is the size of A4 drawing sheet?", "options": ["210×297 mm", "297×420 mm", "420×594 mm", "594×841 mm"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '比例 1:2 表示？', "qEn": "What does scale 1:2 mean?", "options": ["图形比实物大一倍", "图形是实物的一半", "图形与实物相同", "图形是实物的两倍"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '图样上的汉字应写成长仿宋体。', "qEn": "Chinese characters on drawings should be in long imitation Song font.", "answer": True, "diff": 2},
        {"type": "single", 'q': '尺寸标注中，R 表示？', "qEn": "In dimensioning, what does R stand for?", "options": ["直径", "半径", "角度", "弧长"], "answer": 1, "diff": 1},
    ],
    "econ-principles": [
        {"type": "single", 'q': '需求定律表明？', "qEn": "The law of demand states?", "options": ["价格上升需求上升", "价格上升需求下降", "价格与需求无关", "需求决定价格"], "answer": 1, "diff": 1},
        {"type": "single", 'q': 'GDP 的中文含义是？', "qEn": "What does GDP stand for in Chinese?", "options": ["国民生产总值", "国内生产总值", "国民收入", "财政收入"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '供给曲线通常向右上方倾斜。', "qEn": "The supply curve usually slopes upward to the right.", "answer": True, "diff": 1},
        {"type": "single", 'q': '通货膨胀是指？', "qEn": "Inflation refers to?", "options": ["物价持续上涨", "物价持续下降", "货币升值", "失业增加"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '市场失灵的原因不包括？', "qEn": "Which is not a cause of market failure?", "options": ["外部性", "公共物品", "信息不对称", "充分竞争"], "answer": 3, "diff": 2},
        {"type": "judge", 'q': '机会成本是做出选择时放弃的下一个最佳选择的价值。', "qEn": "Opportunity cost is the value of the next best alternative foregone.", "answer": True, "diff": 1},
        {"type": "single", 'q': '完全竞争市场的特征不包括？', "qEn": "Which is not a feature of perfect competition?", "options": ["大量买家和卖家", "产品同质", "信息完全", "产品差异化"], "answer": 3, "diff": 2},
        {"type": "single", 'q': '央行提高利率通常会导致？', "qEn": "When the central bank raises interest rates, it usually causes?", "options": ["投资增加", "消费增加", "投资减少", "出口增加"], "answer": 2, "diff": 1},
        {"type": "judge", 'q': '需求价格弹性衡量需求量对价格变化的敏感度。', "qEn": "Price elasticity of demand measures sensitivity of quantity demanded to price changes.", "answer": True, "diff": 1},
        {"type": "single", 'q': '经济学中的稀缺性指？', "qEn": "Scarcity in economics refers to?", "options": ["资源绝对缺乏", "资源相对于欲望的有限性", "资源过剩", "资源无限"], "answer": 1, "diff": 1},
    ],
    "acct-basic": [
        {"type": "single", 'q': '会计的基本职能是？', "qEn": "What is the basic function of accounting?", "options": ["记账", "反映和监督", "计算税款", "发放工资"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '借贷记账法中,借方表示?', "qEn": "In double-entry bookkeeping, debit represents?", "options": ["资金来源增加", "资金运用增加", "权益增加", "负债增加"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '会计恒等式：资产 = 负债 + 所有者权益。', "qEn": "Accounting equation: Assets = Liabilities + Owner's Equity.", "answer": True, "diff": 1},
        {"type": "single", 'q': '资产负债表反映的是？', "qEn": "What does a balance sheet reflect?", "options": ["某一时期经营成果", "某一时点财务状况", "现金流入流出", "利润分配"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '权责发生制指？', "qEn": "Accrual basis means?", "options": ["按现金收付记账", "按经济业务发生记账", "按收付实现制记账", "按计划记账"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '收入 = 费用 + 利润。', "qEn": "Revenue equals expenses plus profit.", "answer": True, "diff": 1},
        {"type": "single", 'q': '会计期间通常为？', "qEn": "What is a typical accounting period?", "options": ["1 个月", "1 年", "3 个月", "5 年"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '以下哪项属于流动资产？', "qEn": "Which is a current asset?", "options": ["房屋", "机器", "存货", "土地"], "answer": 2, "diff": 1},
        {"type": "judge", 'q': '应收账款属于资产类账户。', "qEn": "Accounts receivable belongs to asset accounts.", "answer": True, "diff": 1},
        {"type": "single", 'q': '计提折旧属于？', "qEn": "Depreciation is?", "options": ["资产增加", "费用增加", "负债增加", "权益增加"], "answer": 1, "diff": 2},
    ],
    "business-law": [
        {"type": "single", 'q': '合同成立的基本要素不包括？', "qEn": "Which is not a basic element of a contract?", "options": ["要约", "承诺", "对价", "公正"], "answer": 3, "diff": 1},
        {"type": "single", 'q': '知识产权不包括？', "qEn": "Intellectual property does not include?", "options": ["专利权", "商标权", "著作权", "财产权"], "answer": 3, "diff": 1},
        {"type": "judge", 'q': '合同当事人地位平等。', "qEn": "Contract parties have equal status.", "answer": True, "diff": 1},
        {"type": "single", 'q': '公司是？', "qEn": "A company is?", "options": ["自然人", "法人", "合伙", "个人独资企业"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '商标权的保护期限通常是？', "qEn": "How long is trademark protection usually?", "options": ["5 年", "10 年", "20 年", "终身"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '侵权行为需要承担民事责任。', "qEn": "Tortious acts require civil liability.", "answer": True, "diff": 1},
        {"type": "single", 'q': '以下哪个不是合同无效的情形？', "qEn": "Which is not a case of contract invalidity?", "options": ["违法合同", "欺诈胁迫", "意思表示真实", "恶意串通"], "answer": 2, "diff": 2},
        {"type": "single", 'q': '股东大会是公司的？', "qEn": "Shareholders' meeting is the company's?", "options": ["执行机构", "权力机构", "监督机构", "管理机构"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '专利分为发明、实用新型和外观设计。', "qEn": "Patents are divided into invention, utility model, and design.", "answer": True, "diff": 1},
        {"type": "single", 'q': '以下哪个属于商法调整对象？', "qEn": "Which is a commercial law subject?", "options": ["婚姻关系", "公司关系", "继承关系", "邻里关系"], "answer": 1, "diff": 1},
    ],
    "info-tech": [
        {"type": "single", 'q': '操作系统是？', "qEn": "What is an operating system?", "options": ["应用软件", "系统软件", "工具软件", "编程语言"], "answer": 1, "diff": 1},
        {"type": "single", 'q': 'IP 地址是？', "qEn": "What is an IP address?", "options": ["网卡地址", "网络协议地址", "MAC 地址", "域名"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': 'RAM 是易失性存储器。', "qEn": "RAM is volatile memory.", "answer": True, "diff": 1},
        {"type": "single", 'q': '以下哪个是输入设备？', "qEn": "Which is an input device?", "options": ["显示器", "打印机", "键盘", "音箱"], "answer": 2, "diff": 1},
        {"type": "single", 'q': '数据库的核心是？', "qEn": "What is the core of a database?", "options": ["数据", "表", "数据库管理系统", "视图"], "answer": 2, "diff": 1},
        {"type": "judge", 'q': '防火墙可以保护网络安全。', "qEn": "Firewalls can protect network security.", "answer": True, "diff": 1},
        {"type": "single", 'q': '1 GB 等于？', "qEn": "1 GB equals?", "options": ["1024 KB", "1024 MB", "1000 MB", "1024 B"], "answer": 1, "diff": 1},
        {"type": "single", 'q': 'HTML 是？', "qEn": "HTML is?", "options": ["编程语言", "标记语言", "数据库", "操作系统"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '云计算通过网络提供可伸缩的 IT 资源。', "qEn": "Cloud computing provides scalable IT resources over the network.", "answer": True, "diff": 1},
        {"type": "single", 'q': '以下哪个是输出设备？', "qEn": "Which is an output device?", "options": ["鼠标", "扫描仪", "显示器", "麦克风"], "answer": 2, "diff": 1},
    ],
    "communication": [
        {"type": "single", 'q': '商务沟通的第一步是？', "qEn": "What is the first step in business communication?", "options": ["倾听", "明确目标", "撰写内容", "发送信息"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '非语言沟通不包括？', "qEn": "Non-verbal communication does not include?", "options": ["表情", "手势", "语调", "邮件"], "answer": 3, "diff": 1},
        {"type": "judge", 'q': '有效倾听是良好沟通的关键。', "qEn": "Effective listening is key to good communication.", "answer": True, "diff": 1},
        {"type": "single", 'q': '7C 原则中不包括？', "qEn": "Which is not in the 7 C's principle?", "options": ["清晰", "简洁", "完整", "复杂"], "answer": 3, "diff": 2},
        {"type": "single", 'q': '会议主持需要？', "qEn": "Meeting facilitation requires?", "options": ["控制时间", "分配任务", "引导讨论", "以上都是"], "answer": 3, "diff": 1},
        {"type": "judge", 'q': '反馈应该是具体的、建设性的。', "qEn": "Feedback should be specific and constructive.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'PPT 演示的核心是？', "qEn": "What is the core of a PPT presentation?", "options": ["精美模板", "动画效果", "清晰传达信息", "丰富文字"], "answer": 2, "diff": 1},
        {"type": "single", 'q': '跨文化沟通需要？', "qEn": "Cross-cultural communication requires?", "options": ["坚持己见", "尊重差异", "回避冲突", "语言优势"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '邮件标题应该简洁明确。', "qEn": "Email subjects should be concise and clear.", "answer": True, "diff": 1},
        {"type": "single", 'q': '演讲中最重要的是？', "qEn": "What is most important in a speech?", "options": ["发音标准", "内容逻辑", "观众互动", "服装得体"], "answer": 1, "diff": 1},
    ],
    "lab-tech": [
        {"type": "single", 'q': '实验室安全第一原则是？', "qEn": "What is the first principle of lab safety?", "options": ["穿戴防护用品", "熟悉操作规程", "保持清洁", "节约资源"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '量筒用于？', "qEn": "A graduated cylinder is used for?", "options": ["称量质量", "测量体积", "测量温度", "加热"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '实验数据应如实记录，不可篡改。', "qEn": "Experimental data should be recorded truthfully and not tampered with.", "answer": True, "diff": 1},
        {"type": "single", 'q': '酒精灯使用完毕后应？', "qEn": "After using an alcohol lamp, you should?", "options": ["用嘴吹灭", "用灯帽盖灭", "直接放置", "加水冷却"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '滴定管读数应视线？', "qEn": "When reading a burette, your eyes should be?", "options": ["俯视", "仰视", "平视", "斜视"], "answer": 2, "diff": 1},
        {"type": "judge", 'q': '实验室中禁止饮食。', "qEn": "Eating and drinking are prohibited in the lab.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'pH 试纸用于测定？', "qEn": "pH paper is used to measure?", "options": ["温度", "酸碱度", "浓度", "密度"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '实验中遇到事故应？', "qEn": "If an accident occurs during an experiment, you should?", "options": ["隐瞒不报", "立即报告老师", "继续实验", "自行处理"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '实验结束后应清洗器具并归位。', "qEn": "After the experiment, clean and return the equipment.", "answer": True, "diff": 1},
        {"type": "single", 'q': '电子天平读数应？', "qEn": "When using an electronic balance, you should?", "options": ["等数值稳定后读数", "立即读数", "估读", "不读数"], "answer": 0, "diff": 1},
    ],
    "history-world": [
        {"type": "single", 'q': '四大文明古国不包括？', "qEn": "Which is not one of the four ancient civilizations?", "options": ["古埃及", "古巴比伦", "古希腊", "古印度"], "answer": 2, "diff": 1},
        {"type": "single", 'q': '文艺复兴起源于？', "qEn": "The Renaissance originated in?", "options": ["法国", "意大利", "英国", "德国"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '哥伦布于 1492 年到达美洲。', "qEn": "Columbus reached America in 1492.", "answer": True, "diff": 1},
        {"type": "single", 'q': '第一次世界大战开始于？', "qEn": "When did World War I begin?", "options": ["1912", "1914", "1916", "1918"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '工业革命最早发生在？', "qEn": "Where did the Industrial Revolution first occur?", "options": ["美国", "法国", "英国", "德国"], "answer": 2, "diff": 1},
        {"type": "judge", 'q': '二战结束于 1945 年。', "qEn": "World War II ended in 1945.", "answer": True, "diff": 1},
        {"type": "single", 'q': '古罗马帝国的官方语言是？', "qEn": "What was the official language of the Roman Empire?", "options": ["希腊语", "拉丁语", "意大利语", "法语"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '苏联解体于？', "qEn": "When did the Soviet Union dissolve?", "options": ["1989", "1991", "1993", "1995"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '丝绸之路连接了东西方文明。', "qEn": "The Silk Road connected Eastern and Western civilizations.", "answer": True, "diff": 1},
        {"type": "single", 'q': '美国独立宣言发表于？', "qEn": "When was the US Declaration of Independence issued?", "options": ["1776", "1789", "1812", "1865"], "answer": 0, "diff": 1},
    ],
    "research-methods": [
        {"type": "single", 'q': '定量研究主要使用？', "qEn": "Quantitative research mainly uses?", "options": ["访谈", "观察", "数据统计", "文本分析"], "answer": 2, "diff": 1},
        {"type": "single", 'q': '文献综述的目的是？', "qEn": "What is the purpose of a literature review?", "options": ["罗列文献", "综合分析已有研究", "批评他人", "展示自己"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '研究问题应当具体、明确。', "qEn": "Research questions should be specific and clear.", "answer": True, "diff": 1},
        {"type": "single", 'q': '抽样方法中，最基本的是？', "qEn": "What is the most basic sampling method?", "options": ["随机抽样", "分层抽样", "系统抽样", "整群抽样"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '实验组和控制组的区别是？', "qEn": "The difference between experimental and control group is?", "options": ["人数不同", "是否接受实验处理", "性别不同", "年龄不同"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '定性研究关注为什么而非多少。', "qEn": "Qualitative research focuses on why rather than how many.", "answer": True, "diff": 1},
        {"type": "single", 'q': '问卷设计应避免？', "qEn": "Questionnaire design should avoid?", "options": ["清晰问题", "引导性问题", "明确选项", "合理长度"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '信度衡量？', "qEn": "Reliability measures?", "options": ["准确性", "一致性", "有效性", "客观性"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '样本量越大，研究结果越可靠。', "qEn": "Larger sample size leads to more reliable research results.", "answer": True, "diff": 1},
        {"type": "single", 'q': '研究伦理不包括？', "qEn": "Research ethics does not include?", "options": ["知情同意", "隐私保护", "数据造假", "公正性"], "answer": 2, "diff": 1},
    ],
    "writing-academic": [
        {"type": "single", 'q': '学术论文的核心结构是？', "qEn": "What is the core structure of an academic paper?", "options": ["标题、摘要、正文、参考文献", "前言、目录、结论", "封面、目录、正文", "标题、关键词、附录"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '摘要应包含？', "qEn": "An abstract should include?", "options": ["研究目的、方法、结果、结论", "详细内容", "所有数据", "图表"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '学术写作应避免使用第一人称。', "qEn": "Academic writing should avoid first person.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'APA 引用格式主要用于？', "qEn": "APA citation format is mainly used in?", "options": ["文学", "社会科学", "自然科学", "工程技术"], "answer": 1, "diff": 2},
        {"type": "single", 'q': '学术语言的特点不包括？', "qEn": "Which is not a feature of academic language?", "options": ["客观", "精确", "口语化", "严谨"], "answer": 2, "diff": 1},
        {"type": "judge", 'q': '引文必须注明出处。', "qEn": "Citations must be attributed.", "answer": True, "diff": 1},
        {"type": "single", 'q': '文献回顾的位置通常在？', "qEn": "Where is the literature review usually located?", "options": ["引言后", "方法前", "结果后", "结论后"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '论文修改应关注？', "qEn": "Paper revision should focus on?", "options": ["仅错别字", "结构和逻辑", "仅格式", "仅语法"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '结论部分不应引入新信息。', "qEn": "The conclusion should not introduce new information.", "answer": True, "diff": 1},
        {"type": "single", 'q': '引言的主要作用是？', "qEn": "The main function of the introduction is?", "options": ["罗列结果", "引出研究问题", "展示数据", "总结全文"], "answer": 1, "diff": 1},
    ],
    "critical-thinking": [
        {"type": "single", 'q': '批判性思维的核心是？', "qEn": "What is the core of critical thinking?", "options": ["盲目相信", "理性分析", "情绪判断", "直觉"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '以下哪个是逻辑谬误？', "qEn": "Which is a logical fallacy?", "options": ["演绎推理", "归纳推理", "稻草人谬误", "类比推理"], "answer": 2, "diff": 1},
        {"type": "judge", 'q': '批判性思维意味着否定一切。', "qEn": "Critical thinking means denying everything.", "answer": False, "diff": 1},
        {"type": "single", 'q': '评价证据时应关注？', "qEn": "When evaluating evidence, focus on?", "options": ["来源可靠性", "数据准确性", "样本量", "以上都是"], "answer": 3, "diff": 1},
        {"type": "single", 'q': '以下哪个不是论证结构？', "qEn": "Which is not an argument structure?", "options": ["前提", "结论", "假设", "修辞"], "answer": 3, "diff": 1},
        {"type": "judge", 'q': '相关关系不等于因果关系。', "qEn": "Correlation does not equal causation.", "answer": True, "diff": 1},
        {"type": "single", 'q': '苏格拉底方法属于？', "qEn": "Socratic method belongs to?", "options": ["记忆技巧", "提问式思维", "记忆术", "填鸭式教学"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '避免确认偏误的方法是？', "qEn": "How to avoid confirmation bias?", "options": ["只看支持自己观点的证据", "主动寻找反证", "坚持己见", "回避不同意见"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '独立思考是批判性思维的重要特征。', "qEn": "Independent thinking is an important feature of critical thinking.", "answer": True, "diff": 1},
        {"type": "single", 'q': '广告中常用的心理手法是？', "qEn": "What psychological technique is commonly used in advertising?", "options": ["诉诸情感", "数据呈现", "专家证言", "以上都是"], "answer": 3, "diff": 1},
    ],
    "art-history": [
        {"type": "single", 'q': '文艺复兴的核心思想是？', "qEn": "What is the core idea of the Renaissance?", "options": ["神权至上", "人文主义", "君权神授", "禁欲主义"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '《蒙娜丽莎》的作者是？', "qEn": "Who is the author of Mona Lisa?", "options": ["米开朗基罗", "达芬奇", "拉斐尔", "伦勃朗"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '印象派起源于法国。', "qEn": "Impressionism originated in France.", "answer": True, "diff": 1},
        {"type": "single", 'q': '巴洛克艺术的特点是？', "qEn": "What characterizes Baroque art?", "options": ["简洁朴素", "华丽动感", "理性严谨", "抽象简约"], "answer": 1, "diff": 2},
        {"type": "single", 'q': '现代主义艺术强调？', "qEn": "Modernist art emphasizes?", "options": ["写实", "创新和个性", "传统", "宗教主题"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '中国画注重写意，西洋画注重写实。', "qEn": "Chinese painting emphasizes expression, Western painting emphasizes realism.", "answer": True, "diff": 1},
        {"type": "single", 'q': '罗丹是著名的？', "qEn": "Rodin is a famous?", "options": ["画家", "雕塑家", "建筑师", "音乐家"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '梵高属于哪个流派？', "qEn": "Van Gogh belongs to which school?", "options": ["印象派", "后印象派", "立体派", "野兽派"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '敦煌壁画属于佛教艺术。', "qEn": "Dunhuang murals belong to Buddhist art.", "answer": True, "diff": 1},
        {"type": "single", 'q': '新古典主义强调？', "qEn": "Neoclassicism emphasizes?", "options": ["情感表达", "理性与秩序", "色彩鲜艳", "抽象形式"], "answer": 1, "diff": 2},
    ],
    "drawing-basic": [
        {"type": "single", 'q': '素描的三大面是？', "qEn": "What are the three main tones in sketching?", "options": ["亮面、灰面、暗面", "上、中、下", "左、中、右", "前、中、后"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '透视的基本类型不包括？', "qEn": "Which is not a basic type of perspective?", "options": ["一点透视", "两点透视", "三点透视", "四点透视"], "answer": 3, "diff": 1},
        {"type": "judge", 'q': '线条是素描的基础。', "qEn": "Lines are the foundation of sketching.", "answer": True, "diff": 1},
        {"type": "single", 'q': '明暗交界线是？', "qEn": "The light-dark boundary is?", "options": ["物体最亮处", "物体最暗处", "亮面与暗面的转折", "投影边缘"], "answer": 2, "diff": 1},
        {"type": "single", 'q': '构图原则不包括？', "qEn": "Composition principles do not include?", "options": ["对比", "平衡", "重复", "随机"], "answer": 3, "diff": 1},
        {"type": "judge", 'q': '速写是快速捕捉对象特征的绘画形式。', "qEn": "Sketching is a drawing form that quickly captures features.", "answer": True, "diff": 1},
        {"type": "single", 'q': '色彩三要素是？', "qEn": "What are the three elements of color?", "options": ["色相、明度、纯度", "红、黄、蓝", "冷、暖、中性", "光、色、形"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '国画用的主要颜料是？', "qEn": "What are the main pigments used in Chinese painting?", "options": ["水彩", "水粉", "国画颜料", "油画颜料"], "answer": 2, "diff": 1},
        {"type": "judge", 'q': '临摹是学习绘画的有效方法。', "qEn": "Copying is an effective way to learn painting.", "answer": True, "diff": 1},
        {"type": "single", 'q': '近大远小是哪种透视规律？', "qEn": "Near large far small is which perspective law?", "options": ["色彩透视", "空气透视", "线性透视", "消失透视"], "answer": 2, "diff": 1},
    ],
    "design-principles": [
        {"type": "single", 'q': '平面设计四原则不包括？', "qEn": "Which is not in the four principles of graphic design?", "options": ["对比", "重复", "对齐", "堆砌"], "answer": 3, "diff": 1},
        {"type": "single", 'q': '版式设计中的出血指？', "qEn": "What is 'bleed' in layout design?", "options": ["文字颜色", "超出裁切线的部分", "图片格式", "页面大小"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '好的设计应当简洁明了。', "qEn": "Good design should be simple and clear.", "answer": True, "diff": 1},
        {"type": "single", 'q': '网格系统的作用是？', "qEn": "What is the function of a grid system?", "options": ["美化版面", "规范版面", "增加成本", "减少可读性"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '品牌设计的核心是？', "qEn": "What is the core of brand design?", "options": ["标志", "色彩", "整体识别", "字体"], "answer": 2, "diff": 1},
        {"type": "judge", 'q': '设计应当以人为本。', "qEn": "Design should be human-centered.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'UI 设计中的'可用性"指？", "qEn": "What is 'usability' in UI design?", "options": ["美观", "易用程度", "颜色搭配", "动画效果"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '字体设计的目的是？', "qEn": "What is the purpose of font design?", "options": ["炫耀技巧", "传递信息", "增加难度", "装饰版面"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '留白是设计的重要手法。', "qEn": "White space is an important design technique.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'Logo 设计最关键的是？', "qEn": "What is most important in logo design?", "options": ["复杂度", "辨识度", "色彩多", "字体多"], "answer": 1, "diff": 1},
    ],
    "color-theory": [
        {"type": "single", 'q': '三原色是？', "qEn": "What are the three primary colors?", "options": ["红黄蓝", "红绿蓝", "黄绿紫", "黑灰白"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '互补色指？', "qEn": "What are complementary colors?", "options": ["相邻颜色", "色环上相对的颜色", "相同颜色", "相似颜色"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '暖色给人前进感，冷色给人后退感。', "qEn": "Warm colors give a sense of advancing, cool colors give a sense of retreating.", "answer": True, "diff": 1},
        {"type": "single", 'q': '明度指？', "qEn": "Brightness refers to?", "options": ["颜色的鲜艳程度", "颜色的明暗", "颜色的种类", "颜色的大小"], "answer": 1, "diff": 1},
        {"type": "single", 'q': 'RGB 模式用于？', "qEn": "RGB mode is used for?", "options": ["印刷", "屏幕显示", "绘画", "雕塑"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '色彩能影响人的情绪。', "qEn": "Color can affect people's emotions.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'CMYK 模式主要用于？', "qEn": "CMYK mode is mainly used for?", "options": ["屏幕", "印刷", "网页", "动画"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '饱和度指？', "qEn": "Saturation refers to?", "options": ["颜色的明亮程度", "颜色的纯度", "颜色的大小", "颜色的冷暖"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '黑与白不属于色彩。', "qEn": "Black and white are not considered colors.", "answer": False, "diff": 1},
        {"type": "single", 'q': '以下哪个是冷色？', "qEn": "Which is a cool color?", "options": ["红", "橙", "蓝", "黄"], "answer": 2, "diff": 1},
    ],
    "digital-tools": [
        {"type": "single", 'q': 'Photoshop 主要用于？', "qEn": "Photoshop is mainly used for?", "options": ["文字处理", "图像处理", "音频编辑", "视频制作"], "answer": 1, "diff": 1},
        {"type": "single", 'q': 'Illustrator 是？', "qEn": "Illustrator is?", "options": ["位图软件", "矢量软件", "视频软件", "音频软件"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': 'Figma 是一款基于浏览器的协作设计工具。', "qEn": "Figma is a browser-based collaborative design tool.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'After Effects 用于？', "qEn": "After Effects is used for?", "options": ["照片处理", "动态图形和特效", "网页设计", "数据库管理"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '以下哪个是 3D 建模软件？', "qEn": "Which is 3D modeling software?", "options": ["Photoshop", "Blender", "Premiere", "Audition"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '云端协作工具可以提高团队效率。', "qEn": "Cloud collaboration tools can improve team efficiency.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'PPT 主要用于？', "qEn": "PPT is mainly used for?", "options": ["编程", "演示文稿", "图片编辑", "财务管理"], "answer": 1, "diff": 1},
        {"type": "single", 'q': 'Canva 的特点是？', "qEn": "What is the feature of Canva?", "options": ["专业级图像处理", "简易的在线设计", "3D 建模", "编程开发"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '短视频剪辑工具包括剪映和 CapCut。', "qEn": "Short video editing tools include Jianying and CapCut.", "answer": True, "diff": 1},
        {"type": "single", 'q': '设计文件常用格式是？', "qEn": "What is a common design file format?", "options": [".exe", ".psd", ".dll", ".bat"], "answer": 1, "diff": 1},
    ],
    "psych-general": [
        {"type": "single", 'q': '心理学主要研究？', "qEn": "Psychology mainly studies?", "options": ["人类行为与心理", "动物行为", "社会结构", "经济发展"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '弗洛伊德属于哪个流派？', "qEn": "Freud belongs to which school?", "options": ["行为主义", "精神分析", "认知心理学", "人本主义"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '感觉是最简单的心理现象。', "qEn": "Sensation is the simplest psychological phenomenon.", "answer": True, "diff": 1},
        {"type": "single", 'q': '记忆的三个基本过程是？', "qEn": "What are the three basic processes of memory?", "options": ["编码、存储、提取", "感觉、知觉、思维", "注意、想象、情感", "动机、需要、意志"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '马斯洛需求层次理论最高层是？', "qEn": "What is the highest level in Maslow's hierarchy?", "options": ["生理需求", "安全需求", "尊重需求", "自我实现"], "answer": 3, "diff": 1},
        {"type": "judge", 'q': '气质是个体与生俱来的心理特征。', "qEn": "Temperament is an innate psychological characteristic.", "answer": True, "diff": 1},
        {"type": "single", 'q': '心理学之父是？', "qEn": "Who is the father of psychology?", "options": ["弗洛伊德", "冯特", "斯金纳", "皮亚杰"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '情绪的基本分类不包括？', "qEn": "Which is not a basic emotion category?", "options": ["快乐", "愤怒", "悲伤", "理性"], "answer": 3, "diff": 1},
        {"type": "judge", 'q': '知觉是感觉的综合。', "qEn": "Perception is the synthesis of sensations.", "answer": True, "diff": 1},
        {"type": "single", 'q': 'IQ 100 表示？', "qEn": "IQ 100 indicates?", "options": ["智力超常", "智力中等", "智力低下", "无法判断"], "answer": 1, "diff": 1},
    ],
    "child-dev": [
        {"type": "single", 'q': '皮亚杰认知发展阶段不包括？', "qEn": "Which is not a Piaget cognitive development stage?", "options": ["感知运动阶段", "前运算阶段", "具体运算阶段", "抽象运算阶段"], "answer": 3, "diff": 1},
        {"type": "single", 'q': '婴儿期是指？', "qEn": "Infancy refers to?", "options": ["0-1 岁", "0-3 岁", "1-3 岁", "3-6 岁"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '依恋是婴儿与照顾者之间的情感联结。', "qEn": "Attachment is the emotional bond between infant and caregiver.", "answer": True, "diff": 1},
        {"type": "single", 'q': '青春期通常发生在？', "qEn": "Adolescence usually occurs during?", "options": ["8-10 岁", "10-19 岁", "20-25 岁", "25-30 岁"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '埃里克森理论关注？', "qEn": "Erikson's theory focuses on?", "options": ["认知发展", "社会发展", "心理社会发展", "语言发展"], "answer": 2, "diff": 2},
        {"type": "judge", 'q': '游戏是儿童学习的重要方式。', "qEn": "Play is an important way for children to learn.", "answer": True, "diff": 1},
        {"type": "single", 'q': '语言发展关键期是？', "qEn": "When is the critical period for language development?", "options": ["0-2 岁", "2-6 岁", "6-12 岁", "12 岁后"], "answer": 0, "diff": 2},
        {"type": "single", 'q': '儿童道德发展理论提出者是？', "qEn": "Who proposed the theory of moral development in children?", "options": ["皮亚杰", "科尔伯格", "维果茨基", "班杜拉"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '儿童发展具有阶段性。', "qEn": "Child development has stages.", "answer": True, "diff": 1},
        {"type": "single", 'q': '新生儿平均体重约？', "qEn": "What is the average weight of a newborn?", "options": ["2 公斤", "3.5 公斤", "5 公斤", "6 公斤"], "answer": 1, "diff": 1},
    ],
    "education-history": [
        {"type": "single", 'q': '中国古代教育经典是？', "qEn": "Which is a classic of ancient Chinese education?", "options": ["《学记》", "《诗经》", "《史记》", "《论语》"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '古希腊著名教育家是？', "qEn": "Who is a famous ancient Greek educator?", "options": ["苏格拉底", "柏拉图", "亚里士多德", "以上都是"], "answer": 3, "diff": 1},
        {"type": "judge", 'q': '中国古代有科举制度。', "qEn": "Ancient China had the imperial examination system.", "answer": True, "diff": 1},
        {"type": "single", 'q': '夸美纽斯是？', "qEn": "Comenius is?", "options": ["古代教育家", "近代教育家", "现代教育家", "当代教育家"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '杜威提出？', "qEn": "Dewey proposed?", "options": ["传统教育", "进步主义教育", "永恒主义教育", "要素主义教育"], "answer": 1, "diff": 2},
        {"type": "judge", 'q': '赫尔巴特被誉为现代教育学之父。', "qEn": "Herbart is called the father of modern pedagogy.", "answer": True, "diff": 1},
        {"type": "single", 'q': '我国近代第一所师范学校是？', "qEn": "What is the first normal school in modern China?", "options": ["京师大学堂", "南洋公学师范院", "北大", "清华"], "answer": 1, "diff": 2},
        {"type": "single", 'q': '孔子提倡？', "qEn": "Confucius advocated?", "options": ["有教无类", "因材施教", "温故知新", "以上都是"], "answer": 3, "diff": 1},
        {"type": "judge", 'q': '素质教育强调全面发展。', "qEn": "Quality education emphasizes all-round development.", "answer": True, "diff": 1},
        {"type": "single", 'q': '现代教育的重要特征是？', "qEn": "What is an important feature of modern education?", "options": ["面向少数人", "普及化", "脱离生活", "重视记忆"], "answer": 1, "diff": 1},
    ],
    "learning-theory": [
        {"type": "single", 'q': '行为主义的代表是？', "qEn": "Who represents behaviorism?", "options": ["斯金纳", "弗洛伊德", "皮亚杰", "马斯洛"], "answer": 0, "diff": 1},
        {"type": "single", 'q': '强化理论属于？', "qEn": "Reinforcement theory belongs to?", "options": ["行为主义", "认知主义", "建构主义", "人本主义"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '建构主义强调学习者的主动性。', "qEn": "Constructivism emphasizes learner initiative.", "answer": True, "diff": 1},
        {"type": "single", 'q': '认知主义关注？', "qEn": "Cognitivism focuses on?", "options": ["外部刺激", "内部心理过程", "无意识", "生理反应"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '观察学习的提出者是？', "qEn": "Who proposed observational learning?", "options": ["班杜拉", "斯金纳", "皮亚杰", "维果茨基"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '有意义学习是新知识与已有知识建立联系。', "qEn": "Meaningful learning connects new knowledge with existing knowledge.", "answer": True, "diff": 1},
        {"type": "single", 'q': '最近发展区的提出者是？', "qEn": "Who proposed the zone of proximal development?", "options": ["皮亚杰", "维果茨基", "布鲁纳", "奥苏贝尔"], "answer": 1, "diff": 2},
        {"type": "single", 'q': '正强化是？', "qEn": "Positive reinforcement is?", "options": ["施加厌恶刺激", "给予愉快刺激", "取消愉快刺激", "无刺激"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '学习风格影响学习效果。', "qEn": "Learning style affects learning outcomes.", "answer": True, "diff": 1},
        {"type": "single", 'q': '元认知是？', "qEn": "Metacognition is?", "options": ["对学习的认识", "对认知的认知", "对记忆的认识", "对情感的认识"], "answer": 1, "diff": 2},
    ],
    "classroom-mgmt": [
        {"type": "single", 'q': '课堂管理的核心目标是？', "qEn": "What is the core goal of classroom management?", "options": ["控制学生", "营造良好学习环境", "惩罚违纪", "完成教学任务"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '制定课堂规则应在？', "qEn": "When should classroom rules be set?", "options": ["学期末", "学期初", "出现问题时", "随意"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '积极倾听能促进师生关系。', "qEn": "Active listening promotes teacher-student relationships.", "answer": True, "diff": 1},
        {"type": "single", 'q': '处理学生违纪行为应？', "qEn": "How should student misbehavior be handled?", "options": ["立即严厉批评", "了解情况后处理", "当众羞辱", "置之不理"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '课堂提问应？', "qEn": "Classroom questions should?", "options": ["只问好学生", "面向全体学生", "难度统一", "不需要等待"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '良好的课堂氛围能提高学习效果。', "qEn": "A positive classroom atmosphere improves learning.", "answer": True, "diff": 1},
        {"type": "single", 'q': '时间管理是课堂管理的？', "qEn": "Time management is?", "options": ["可选技能", "重要组成部分", "与教学无关", "浪费时间"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '表扬学生应？', "qEn": "Praising students should be?", "options": ["泛泛而谈", "具体真诚", "千篇一律", "随意"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '差异化教学是课堂管理的重要策略。', "qEn": "Differentiated instruction is an important classroom management strategy.", "answer": True, "diff": 1},
        {"type": "single", 'q': '应对突发事件应？', "qEn": "How to handle unexpected events?", "options": ["惊慌失措", "冷静处理", "假装没看见", "大声训斥"], "answer": 1, "diff": 1},
    ],
    "diversity": [
        {"type": "single", 'q': '多元文化教育的核心是？', "qEn": "What is the core of multicultural education?", "options": ["文化同化", "尊重文化差异", "文化隔离", "文化优越"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '文化敏感性指？', "qEn": "Cultural sensitivity refers to?", "options": ["对文化差异的察觉", "对所有文化的认同", "文化优越感", "文化排斥"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '多元文化教育促进社会公平。', "qEn": "Multicultural education promotes social equity.", "answer": True, "diff": 1},
        {"type": "single", 'q': '双语教学有利于？', "qEn": "Bilingual teaching is beneficial for?", "options": ["语言发展", "文化理解", "认知发展", "以上都是"], "answer": 3, "diff": 1},
        {"type": "single", 'q': '教师应避免？', "qEn": "Teachers should avoid?", "options": ["文化偏见", "文化包容", "文化尊重", "多元视角"], "answer": 0, "diff": 1},
        {"type": "judge", 'q': '每个学生都应得到公平的教育机会。', "qEn": "Every student should have equal educational opportunities.", "answer": True, "diff": 1},
        {"type": "single", 'q': '文化回应式教学强调？', "qEn": "Culturally responsive teaching emphasizes?", "options": ["忽视文化", "利用学生文化背景", "统一教学", "填鸭式教学"], "answer": 1, "diff": 1},
        {"type": "single", 'q': '学校应？', "qEn": "Schools should?", "options": ["排斥少数族裔", "包容多元文化", "强制同化", "区分对待"], "answer": 1, "diff": 1},
        {"type": "judge", 'q': '刻板印象会影响教育公平。', "qEn": "Stereotypes affect educational equity.", "answer": True, "diff": 1},
        {"type": "single", 'q': '全球公民教育旨在？', "qEn": "Global citizenship education aims to?", "options": ["强化民族主义", "培养国际视野", "排斥外来文化", "文化孤立"], "answer": 1, "diff": 1},
    ],
}

# 课程中文名映射
COURSE_NAMES = {
    "math-algebra": "代数基础", "math-calc1": "微积分I", "math-calc2": "微积分II",
    "math-discrete": "离散数学入门", "math-stat": "统计学入门",
    "physics-mech": "力学基础", "physics-em": "电磁学",
    "chem-general": "普通化学", "chem-organic": "有机化学入门",
    "bio-general": "普通生物学", "prog-basic": "编程入门",
    "logic-reason": "逻辑推理", "digital-literacy": "数字素养",
    "eng-graphics": "工程制图", "econ-principles": "经济学原理",
    "acct-basic": "会计学基础", "business-law": "商法入门",
    "info-tech": "信息技术基础", "communication": "商务沟通",
    "lab-tech": "实验室技术", "history-world": "世界历史",
    "research-methods": "研究方法", "writing-academic": "学术写作",
    "critical-thinking": "批判性思维", "art-history": "艺术史",
    "drawing-basic": "绘画基础", "design-principles": "设计原理",
    "color-theory": "色彩理论", "digital-tools": "数字工具",
    "psych-general": "普通心理学", "child-dev": "儿童发展",
    "education-history": "教育史", "learning-theory": "学习理论",
    "classroom-mgmt": "课堂管理", "diversity": "多元文化教育",
}

# 生成题目JSON
def generate_questions():
    questions = []
    for course_id, qs in QUESTIONS_DATA.items():
        course_name = COURSE_NAMES.get(course_id, course_id)
        for idx, q in enumerate(qs):
            options = q.get("options_real", q["options"])
            questions.append({
                "id": f"{course_id}-{idx+1:03d}",
                "courseId": course_id,
                "courseName": course_name,
                "type": q["type"],
                "question": q["q"],
                "questionEn": q["qEn"],
                "options": options,
                "answer": q["answer"],
                "explanation": "",
                "difficulty": q["diff"]
            })
    return questions

# 写入文件
if __name__ == "__main__":
    qs = generate_questions()
    import json
    with open("/workspace/prerequisite/quiz/data/questions.json", "w", encoding="utf-8") as f:
        json.dump(qs, f, ensure_ascii=False, indent=2)
    print(f"生成题目: {len(qs)} 道")
    print(f"覆盖课程: {len(QUESTIONS_DATA)} 门")
